const COMPANY_NAME = 'Rhythm Nexus';
const COMPANY_EMAIL = 'rhythmnexusco@gmail.com';
const COMPANY_PHONE = '+65 8835 2089';

const POLICY_TRANSLATIONS = {
  en: {
    navTerms: 'Terms',
    navPrivacy: 'Privacy',
    termsTitle: 'Terms of Service',
    privacyTitle: 'Privacy Policy',
    updated: 'Last updated: 24 February 2026',
    termsText: 'By visiting this website and/or placing an order, you agree to these Terms of Service. You must be at least 18 years old, or the age of majority in your jurisdiction. We may change products, limit quantities, refuse service, or cancel suspicious or erroneous orders. Pricing and product descriptions may be updated without notice. Shipping timelines are estimates only, and delays caused by customs, carriers, taxes, weather, or incorrect customer details are outside our control. Risk transfers upon delivery. For EU/EEA/Switzerland consumers, mandatory local consumer protections and withdrawal rights apply according to applicable law. All website content (logos, text, images, graphics, and code) is protected intellectual property and may not be copied or redistributed without written consent. To the fullest extent permitted by law, our liability is limited to the amount paid for the relevant order. These terms are governed by the laws of Singapore, without prejudice to mandatory consumer protections in your local jurisdiction.',
    privacyText: 'This Privacy Policy applies to users in the EU, EEA, Switzerland, the United States, and other supported regions. We collect data you provide (name, email, phone number, shipping/billing details, and order information) and technical data collected automatically (IP address, browser/device data, cookies, and usage data). We process data for order fulfilment, customer service, fraud prevention, legal compliance, and service improvement; legal bases include contract, legal obligation, legitimate interests, and consent where required. We may share data with payment processors, shipping partners, IT providers, and support platforms only as needed, and we do not sell personal data. For users in California and other US states with similar laws, rights may include access, deletion, correction, opt-out rights where applicable, and non-discrimination. For EU/EEA/Swiss users, rights include access, rectification, erasure, restriction, objection, portability, and consent withdrawal. We retain data only as long as necessary for operations, tax/accounting obligations, and legal dispute handling. Where data is transferred internationally, we use lawful safeguards including Standard Contractual Clauses where required. Security controls include encryption in transit, access controls, and secure payment integrations; no method is 100% secure.'
  },
  de: {
    navTerms: 'Nutzungsbedingungen', navPrivacy: 'Datenschutz', termsTitle: 'Nutzungsbedingungen', privacyTitle: 'Datenschutzerklärung', updated: 'Zuletzt aktualisiert: 24. Februar 2026', termsText: 'Durch die Nutzung der Dienste von Rhythm Nexus stimmen Sie zu, korrekte Bestell- und Kontaktdaten bereitzustellen, die Zoll- und Steuervorschriften des Ziellandes einzuhalten und die Website rechtmäßig zu nutzen. Lieferzeiten sind Schätzungen; Verzögerungen durch Zoll, Postdienstleister, Wetter oder andere Ereignisse außerhalb unserer Kontrolle sind möglich. Wir können Bestellungen stornieren und erstatten, wenn erforderliche Angaben fehlen oder ein Versand nicht sicher abgeschlossen werden kann. Produkt-, Versand- und Supportrichtlinien auf dieser Website sind Bestandteil dieser Bedingungen.', privacyText: 'Wir erfassen die für Bestellabwicklung und Anfragen erforderlichen Daten, einschließlich Name, E-Mail, Telefonnummer, Bestellreferenzen, Zieldaten und Tracking-Informationen. Diese Daten verwenden wir zur Auftragsabwicklung, Kundenbetreuung, Betrugsprävention, Einhaltung gesetzlicher Pflichten und Verbesserung unserer Dienste. Wir verkaufen keine personenbezogenen Daten. Daten werden nur bei Bedarf mit Logistikpartnern, Zahlungsplattformen oder Behörden geteilt. Soweit anwendbar, können Sie Auskunft, Berichtigung oder Löschung Ihrer Daten anfordern.'
  },
  fr: {
    navTerms: 'Conditions', navPrivacy: 'Confidentialité', termsTitle: 'Conditions d’utilisation', privacyTitle: 'Politique de confidentialité', updated: 'Dernière mise à jour : 24 février 2026', termsText: 'En utilisant les services de Rhythm Nexus, vous acceptez de fournir des informations de commande et de contact exactes, de respecter les règles douanières et fiscales du pays de destination, et d’utiliser le site de manière légale. Les délais de livraison sont estimatifs et peuvent varier en raison des douanes, des opérateurs postaux, de la météo ou d’autres facteurs hors de notre contrôle. Nous pouvons annuler et rembourser une commande si des informations requises manquent ou si l’expédition ne peut pas être finalisée en toute sécurité. Les politiques produit, expédition et assistance publiées sur ce site font partie de ces conditions.', privacyText: 'Nous collectons les informations nécessaires au traitement des commandes et aux réponses aux demandes : nom, e-mail, téléphone, références de commande, détails de destination et informations de suivi. Ces données sont utilisées pour l’exécution des commandes, l’assistance client, la prévention de la fraude, la conformité légale et l’amélioration du service. Nous ne vendons pas les données personnelles. Les données peuvent être partagées avec des partenaires logistiques, plateformes de paiement ou autorités uniquement si nécessaire. Vous pouvez demander l’accès, la correction ou la suppression de vos données lorsque cela s’applique.'
  },
  es: {
    navTerms: 'Términos', navPrivacy: 'Privacidad', termsTitle: 'Términos de servicio', privacyTitle: 'Política de privacidad', updated: 'Última actualización: 24 de febrero de 2026', termsText: 'Al usar los servicios de Rhythm Nexus, aceptas proporcionar datos de pedido y contacto precisos, cumplir con las normas aduaneras y fiscales del país de destino, y usar el sitio de forma legal. Los plazos de entrega son estimados y pueden verse afectados por aduanas, operadores postales, clima u otros eventos fuera de nuestro control. Podemos cancelar y reembolsar pedidos cuando falten datos obligatorios o no sea posible completar el envío con seguridad. Las políticas de producto, envío y soporte publicadas en este sitio forman parte de estos términos.', privacyText: 'Recopilamos la información necesaria para procesar pedidos y responder consultas, incluyendo nombre, correo, teléfono, referencias de pedido, datos de destino e información de seguimiento. Usamos estos datos para cumplimiento de pedidos, soporte al cliente, prevención de fraude, cumplimiento legal y mejora del servicio. No vendemos datos personales. Los datos pueden compartirse con socios logísticos, plataformas de pago o autoridades solo cuando sea necesario para prestar el servicio o cumplir obligaciones legales. Puedes solicitar acceso, corrección o eliminación de tus datos cuando corresponda.'
  },
  ja: {
    navTerms: '利用規約', navPrivacy: 'プライバシー', termsTitle: '利用規約', privacyTitle: 'プライバシーポリシー', updated: '最終更新日: 2026年2月24日', termsText: 'Rhythm Nexus のサービスを利用することで、正確な注文情報と連絡先情報の提供、配送先の関税・税務規則の遵守、ならびに法令に従ったサイト利用に同意したものとみなされます。配送日数は目安であり、税関、郵便事業者、天候、その他当社管理外の事情により遅延する場合があります。必要情報が不足している場合や安全に発送を完了できない場合、当社は注文をキャンセルし返金することがあります。本サイトに記載された商品・配送・サポート方針は本規約の一部です。', privacyText: '当社は注文処理と問い合わせ対応のために、氏名、メール、電話番号、注文参照情報、配送先情報、追跡関連情報を取得します。これらは注文履行、顧客サポート、不正防止、法令遵守、サービス改善のために利用されます。個人データを販売することはありません。サービス提供または法的義務の履行に必要な場合に限り、物流パートナー、決済プラットフォーム、当局へ共有することがあります。適用される範囲で、アクセス・訂正・削除を請求できます。'
  },
  zh: {
    navTerms: '服务条款', navPrivacy: '隐私政策', termsTitle: '服务条款', privacyTitle: '隐私政策', updated: '最后更新：2026年2月24日', termsText: '使用 Rhythm Nexus 服务即表示您同意提供准确的订单与联系方式，遵守目的地国家/地区的海关与税务规定，并合法使用本网站。配送时效为预计时间，可能因海关、邮政承运商、天气或其他非我方可控因素而延迟。若缺少必要信息或无法安全完成发货，我们可能取消订单并退款。网站上公布的产品、运输与客服政策均构成本条款的一部分。', privacyText: '我们会收集处理订单和回复咨询所需的信息，包括姓名、电子邮箱、电话号码、订单编号、目的地信息及物流追踪相关信息。该等信息用于订单履约、客户支持、反欺诈、法律合规及服务优化。我们不会出售个人数据。仅在履行服务或满足法律义务所必需时，才会与物流合作方、支付平台或监管机构共享数据。在适用法律范围内，您可申请访问、更正或删除个人数据。'
  },
  'zh-hant': {
    navTerms: '服務條款', navPrivacy: '隱私政策', termsTitle: '服務條款', privacyTitle: '隱私政策', updated: '最後更新：2026年2月24日', termsText: '使用 Rhythm Nexus 服務即表示您同意提供正確的訂單與聯絡資料、遵守目的地國家/地區的海關與稅務規定，並合法使用本網站。配送時效為預估值，可能因海關、郵政業者、天候或其他非我方可控因素而延遲。若缺少必要資訊或無法安全完成出貨，我們可能取消訂單並退款。網站上的商品、運送與客服政策皆屬本條款之一部分。', privacyText: '我們會蒐集處理訂單與回覆詢問所需的資料，包括姓名、電子郵件、電話、訂單編號、目的地資料與追蹤相關資訊。這些資料用於履行訂單、客戶服務、反詐欺、法規遵循與服務改善。我們不會出售個人資料。僅在提供服務或履行法律義務所需時，才會與物流夥伴、支付平台或主管機關分享資料。於適用法律範圍內，您可要求查閱、更正或刪除個人資料。'
  },
  pt: {
    navTerms: 'Termos', navPrivacy: 'Privacidade', termsTitle: 'Termos de Serviço', privacyTitle: 'Política de Privacidade', updated: 'Última atualização: 24 de fevereiro de 2026', termsText: 'Ao usar os serviços da Rhythm Nexus, você concorda em fornecer informações corretas de pedido e contato, cumprir regras alfandegárias e fiscais do país de destino e usar o site de forma legal. Os prazos de entrega são estimativas e podem sofrer atrasos por alfândega, operadores postais, clima ou outros fatores fora do nosso controle. Podemos cancelar e reembolsar pedidos quando dados obrigatórios estiverem ausentes ou quando o envio não puder ser concluído com segurança. As políticas de produto, envio e suporte deste site fazem parte destes termos.', privacyText: 'Coletamos os dados necessários para processar pedidos e responder solicitações, incluindo nome, e-mail, telefone, referências de pedido, destino e informações de rastreamento. Usamos esses dados para cumprimento de pedidos, suporte, prevenção de fraude, conformidade legal e melhoria de serviço. Não vendemos dados pessoais. Os dados podem ser compartilhados com parceiros logísticos, plataformas de pagamento ou autoridades somente quando necessário. Você pode solicitar acesso, correção ou exclusão dos seus dados quando aplicável.'
  },
  hi: {
    navTerms: 'नियम', navPrivacy: 'गोपनीयता', termsTitle: 'सेवा की शर्तें', privacyTitle: 'गोपनीयता नीति', updated: 'अंतिम अपडेट: 24 फ़रवरी 2026', termsText: 'Rhythm Nexus सेवाओं का उपयोग करके आप सही ऑर्डर और संपर्क जानकारी देने, गंतव्य देश के कस्टम/टैक्स नियमों का पालन करने और वेबसाइट का वैध उपयोग करने के लिए सहमत होते हैं। डिलीवरी समय अनुमानित है और कस्टम, डाक सेवा, मौसम या अन्य बाहरी कारणों से देरी हो सकती है। आवश्यक जानकारी न होने या सुरक्षित रूप से शिपमेंट पूरा न होने पर हम ऑर्डर रद्द कर रिफंड कर सकते हैं। इस साइट पर दर्शाई गई उत्पाद, शिपिंग और सपोर्ट नीतियाँ इन शर्तों का हिस्सा हैं।', privacyText: 'हम ऑर्डर प्रोसेसिंग और पूछताछ उत्तर देने हेतु आवश्यक जानकारी एकत्र करते हैं, जैसे नाम, ईमेल, फोन नंबर, ऑर्डर संदर्भ, गंतव्य विवरण और ट्रैकिंग जानकारी। यह डेटा ऑर्डर पूर्ति, ग्राहक सहायता, धोखाधड़ी रोकथाम, कानूनी अनुपालन और सेवा सुधार के लिए उपयोग होता है। हम व्यक्तिगत डेटा बेचते नहीं हैं। आवश्यकता होने पर ही लॉजिस्टिक्स पार्टनर, भुगतान प्लेटफ़ॉर्म या प्राधिकरण के साथ डेटा साझा किया जाता है। लागू कानून के अनुसार आप अपने डेटा की पहुँच, संशोधन या हटाने का अनुरोध कर सकते हैं।'
  },
  th: {
    navTerms: 'ข้อกำหนด', navPrivacy: 'ความเป็นส่วนตัว', termsTitle: 'ข้อกำหนดการให้บริการ', privacyTitle: 'นโยบายความเป็นส่วนตัว', updated: 'อัปเดตล่าสุด: 24 กุมภาพันธ์ 2026', termsText: 'เมื่อใช้บริการของ Rhythm Nexus ถือว่าคุณยอมรับที่จะให้ข้อมูลคำสั่งซื้อและข้อมูลติดต่อที่ถูกต้อง ปฏิบัติตามกฎศุลกากรและภาษีของประเทศปลายทาง และใช้งานเว็บไซต์อย่างถูกต้องตามกฎหมาย ระยะเวลาจัดส่งเป็นเพียงการประมาณ และอาจล่าช้าจากศุลกากร ผู้ให้บริการไปรษณีย์ สภาพอากาศ หรือปัจจัยอื่นที่อยู่นอกการควบคุมของเรา เราอาจยกเลิกและคืนเงินคำสั่งซื้อหากข้อมูลจำเป็นไม่ครบถ้วนหรือไม่สามารถจัดส่งได้อย่างปลอดภัย นโยบายสินค้า การจัดส่ง และการสนับสนุนที่ระบุบนเว็บไซต์นี้ถือเป็นส่วนหนึ่งของข้อกำหนดนี้', privacyText: 'เราเก็บข้อมูลที่จำเป็นต่อการดำเนินการคำสั่งซื้อและการตอบข้อสอบถาม เช่น ชื่อ อีเมล หมายเลขโทรศัพท์ ข้อมูลอ้างอิงคำสั่งซื้อ รายละเอียดปลายทาง และข้อมูลติดตามพัสดุ เราใช้ข้อมูลดังกล่าวเพื่อดำเนินการคำสั่งซื้อ บริการลูกค้า ป้องกันการทุจริต ปฏิบัติตามกฎหมาย และพัฒนาบริการ เราไม่ขายข้อมูลส่วนบุคคล ข้อมูลอาจถูกแบ่งปันกับพันธมิตรขนส่ง แพลตฟอร์มการชำระเงิน หรือหน่วยงานที่เกี่ยวข้องเฉพาะเมื่อจำเป็น คุณสามารถขอเข้าถึง แก้ไข หรือขอลบข้อมูลได้ตามกฎหมายที่ใช้บังคับ'
  },
  ms: {
    navTerms: 'Terma', navPrivacy: 'Privasi', termsTitle: 'Terma Perkhidmatan', privacyTitle: 'Dasar Privasi', updated: 'Kemas kini terakhir: 24 Februari 2026', termsText: 'Dengan menggunakan perkhidmatan Rhythm Nexus, anda bersetuju untuk memberikan maklumat pesanan dan hubungan yang tepat, mematuhi peraturan kastam dan cukai negara destinasi, dan menggunakan laman web secara sah. Tempoh penghantaran adalah anggaran dan boleh lewat disebabkan kastam, operator pos, cuaca atau faktor di luar kawalan kami. Kami boleh membatalkan dan memulangkan bayaran jika maklumat wajib tidak lengkap atau penghantaran tidak dapat diselesaikan dengan selamat. Polisi produk, penghantaran dan sokongan di laman ini adalah sebahagian daripada terma ini.', privacyText: 'Kami mengumpul data yang diperlukan untuk memproses pesanan dan menjawab pertanyaan, termasuk nama, e-mel, nombor telefon, rujukan pesanan, butiran destinasi dan maklumat penjejakan. Data ini digunakan untuk pemenuhan pesanan, sokongan pelanggan, pencegahan penipuan, pematuhan undang-undang dan penambahbaikan perkhidmatan. Kami tidak menjual data peribadi. Data boleh dikongsi dengan rakan logistik, platform pembayaran atau pihak berkuasa hanya apabila perlu. Anda boleh meminta akses, pembetulan atau pemadaman data peribadi anda jika berkenaan.'
  },
  nl: {
    navTerms: 'Voorwaarden', navPrivacy: 'Privacy', termsTitle: 'Servicevoorwaarden', privacyTitle: 'Privacybeleid', updated: 'Laatst bijgewerkt: 24 februari 2026', termsText: 'Door Rhythm Nexus te gebruiken, stem je ermee in correcte bestel- en contactgegevens te geven, de douane- en belastingregels van het bestemmingsland na te leven en de website rechtmatig te gebruiken. Levertijden zijn schattingen en kunnen vertragen door douane, postoperatoren, weer of andere factoren buiten onze controle. We kunnen bestellingen annuleren en terugbetalen als verplichte gegevens ontbreken of verzending niet veilig kan worden afgerond. Product-, verzend- en supportbeleid op deze website maken deel uit van deze voorwaarden.', privacyText: 'We verzamelen informatie die nodig is voor orderverwerking en klantvragen, waaronder naam, e-mail, telefoonnummer, orderreferenties, bestemmingsgegevens en trackinginformatie. Deze gegevens gebruiken we voor orderafhandeling, klantenservice, fraudepreventie, wettelijke naleving en serviceverbetering. We verkopen geen persoonsgegevens. Gegevens kunnen alleen worden gedeeld met logistieke partners, betaalplatformen of autoriteiten wanneer dat noodzakelijk is. Je kunt toegang, correctie of verwijdering van je gegevens aanvragen waar van toepassing.'
  },
  id: {
    navTerms: 'Ketentuan', navPrivacy: 'Privasi', termsTitle: 'Ketentuan Layanan', privacyTitle: 'Kebijakan Privasi', updated: 'Terakhir diperbarui: 24 Februari 2026', termsText: 'Dengan menggunakan layanan Rhythm Nexus, Anda setuju untuk memberikan informasi pesanan dan kontak yang akurat, mematuhi aturan bea cukai dan pajak negara tujuan, serta menggunakan situs secara sah. Waktu pengiriman adalah estimasi dan dapat terlambat karena bea cukai, operator pos, cuaca, atau faktor lain di luar kendali kami. Kami dapat membatalkan dan mengembalikan dana pesanan jika data wajib tidak lengkap atau pengiriman tidak dapat diselesaikan dengan aman. Kebijakan produk, pengiriman, dan dukungan di situs ini merupakan bagian dari ketentuan ini.', privacyText: 'Kami mengumpulkan data yang diperlukan untuk memproses pesanan dan menanggapi pertanyaan, termasuk nama, email, nomor telepon, referensi pesanan, detail tujuan, dan informasi pelacakan. Data digunakan untuk pemenuhan pesanan, dukungan pelanggan, pencegahan penipuan, kepatuhan hukum, dan peningkatan layanan. Kami tidak menjual data pribadi. Data hanya dibagikan kepada mitra logistik, platform pembayaran, atau otoritas jika diperlukan. Anda dapat meminta akses, perbaikan, atau penghapusan data pribadi sesuai ketentuan yang berlaku.'
  },
  cs: {
    navTerms: 'Podmínky', navPrivacy: 'Soukromí', termsTitle: 'Podmínky služby', privacyTitle: 'Zásady ochrany osobních údajů', updated: 'Poslední aktualizace: 24. února 2026', termsText: 'Používáním služeb Rhythm Nexus souhlasíte s poskytnutím přesných objednávkových a kontaktních údajů, dodržováním celních a daňových pravidel cílové země a zákonným používáním webu. Dodací lhůty jsou orientační a mohou se zpozdit kvůli celnímu řízení, poštovním operátorům, počasí nebo jiným okolnostem mimo naši kontrolu. Objednávku můžeme zrušit a vrátit platbu, pokud chybí povinné údaje nebo nelze zásilku bezpečně dokončit. Zásady produktů, dopravy a podpory uvedené na tomto webu jsou součástí těchto podmínek.', privacyText: 'Shromažďujeme údaje potřebné ke zpracování objednávek a odpovědím na dotazy, včetně jména, e-mailu, telefonního čísla, referencí objednávky, údajů o destinaci a informací o sledování. Data používáme pro vyřízení objednávek, zákaznickou podporu, prevenci podvodů, splnění právních povinností a zlepšování služeb. Osobní údaje neprodáváme. Údaje mohou být sdíleny s logistickými partnery, platebními platformami nebo úřady pouze v nezbytném rozsahu. Pokud je to relevantní, můžete požádat o přístup, opravu nebo výmaz svých údajů.'
  },
  it: {
    navTerms: 'Termini', navPrivacy: 'Privacy', termsTitle: 'Termini di servizio', privacyTitle: 'Informativa sulla privacy', updated: 'Ultimo aggiornamento: 24 febbraio 2026', termsText: 'Utilizzando i servizi di Rhythm Nexus, accetti di fornire informazioni di ordine e contatto accurate, rispettare le regole doganali e fiscali del paese di destinazione e usare il sito in modo lecito. I tempi di consegna sono stimati e possono subire ritardi dovuti a dogana, operatori postali, meteo o altri eventi fuori dal nostro controllo. Possiamo annullare e rimborsare ordini quando mancano dati obbligatori o la spedizione non può essere completata in sicurezza. Le politiche di prodotto, spedizione e assistenza presenti su questo sito fanno parte dei presenti termini.', privacyText: 'Raccogliamo i dati necessari per elaborare ordini e rispondere alle richieste, inclusi nome, e-mail, numero di telefono, riferimenti ordine, dettagli di destinazione e informazioni di tracciamento. Usiamo questi dati per evasione ordini, supporto clienti, prevenzione frodi, conformità legale e miglioramento del servizio. Non vendiamo dati personali. I dati possono essere condivisi con partner logistici, piattaforme di pagamento o autorità solo quando necessario. Se applicabile, puoi richiedere accesso, rettifica o cancellazione dei tuoi dati.'
  },
  he: {
    navTerms: 'תנאים', navPrivacy: 'פרטיות', termsTitle: 'תנאי שימוש', privacyTitle: 'מדיניות פרטיות', updated: 'עודכן לאחרונה: 24 בפברואר 2026', termsText: 'בשימוש בשירותי Rhythm Nexus אתה מסכים לספק פרטי הזמנה ויצירת קשר מדויקים, לעמוד בכללי מכס ומס של מדינת היעד, ולהשתמש באתר באופן חוקי. זמני אספקה הם הערכה בלבד ועלולים להתעכב עקב מכס, מפעילי דואר, מזג אוויר או נסיבות אחרות שאינן בשליטתנו. אנו רשאים לבטל הזמנה ולהחזיר תשלום אם חסרים פרטים נדרשים או שלא ניתן להשלים משלוח בבטחה. מדיניות המוצר, המשלוח והתמיכה המופיעה באתר זה מהווה חלק מתנאים אלה.', privacyText: 'אנו אוספים מידע הנדרש לעיבוד הזמנות ומענה לפניות, כולל שם, דוא"ל, מספר טלפון, מזהי הזמנה, פרטי יעד ומידע מעקב. המידע משמש למילוי הזמנות, תמיכת לקוחות, מניעת הונאה, עמידה בדרישות חוק ושיפור השירות. איננו מוכרים מידע אישי. מידע עשוי להיות משותף עם שותפי לוגיסטיקה, פלטפורמות תשלום או רשויות רק בעת הצורך. בהתאם לדין החל, ניתן לבקש גישה, תיקון או מחיקה של המידע האישי.'
  },
  ga: {
    navTerms: 'Téarmaí', navPrivacy: 'Príobháideachas', termsTitle: 'Téarmaí Seirbhíse', privacyTitle: 'Polasaí Príobháideachais', updated: 'Nuashonraithe deireanach: 24 Feabhra 2026', termsText: 'Trí sheirbhísí Rhythm Nexus a úsáid, aontaíonn tú faisnéis ordaithe agus teagmhála chruinn a sholáthar, rialacha custaim agus cánach na tíre cinn scríbe a chomhlíonadh, agus an suíomh a úsáid go dleathach. Is meastacháin iad amanna seachadta agus d’fhéadfadh moilleanna tarlú mar gheall ar chustaim, oibreoirí poist, aimsir nó tosca eile lasmuigh dár smacht. Féadfaimid ordú a chur ar ceal agus aisíocaíocht a dhéanamh má tá sonraí riachtanacha ar iarraidh nó mura féidir an loingsiú a chríochnú go sábháilte. Is cuid de na téarmaí seo iad beartais táirge, loingseoireachta agus tacaíochta ar an suíomh seo.', privacyText: 'Bailímid an fhaisnéis atá riachtanach chun orduithe a phróiseáil agus fiosruithe a fhreagairt, lena n-áirítear ainm, ríomhphost, uimhir theileafóin, tagairtí ordaithe, sonraí cinn scríbe agus faisnéis rianaithe. Úsáidtear an fhaisnéis seo do chomhlíonadh ordaithe, tacaíocht do chustaiméirí, cosc calaoise, comhlíonadh dlí agus feabhsú seirbhíse. Ní dhíolaimid sonraí pearsanta. Is féidir sonraí a roinnt le comhpháirtithe lóistíochta, ardáin íocaíochta nó údaráis nuair is gá amháin. Féadfaidh tú rochtain, ceartú nó scriosadh do shonraí a iarraidh nuair is infheidhme.'
  },
  pl: {
    navTerms: 'Regulamin', navPrivacy: 'Prywatność', termsTitle: 'Warunki korzystania z usługi', privacyTitle: 'Polityka prywatności', updated: 'Ostatnia aktualizacja: 24 lutego 2026', termsText: 'Korzystając z usług Rhythm Nexus, zgadzasz się podawać prawidłowe dane zamówienia i kontaktowe, przestrzegać przepisów celnych i podatkowych kraju docelowego oraz korzystać ze strony zgodnie z prawem. Terminy dostawy są orientacyjne i mogą ulec opóźnieniu z powodu odprawy celnej, operatorów pocztowych, pogody lub innych czynników poza naszą kontrolą. Możemy anulować zamówienie i zwrócić płatność, jeśli brakuje wymaganych danych lub wysyłka nie może zostać bezpiecznie zrealizowana. Zasady produktu, wysyłki i wsparcia na tej stronie stanowią część niniejszych warunków.', privacyText: 'Zbieramy dane potrzebne do realizacji zamówień i odpowiadania na zapytania, w tym imię i nazwisko, e-mail, numer telefonu, referencje zamówienia, dane miejsca docelowego i informacje śledzenia. Dane wykorzystujemy do realizacji zamówień, obsługi klienta, zapobiegania nadużyciom, zgodności z prawem i ulepszania usług. Nie sprzedajemy danych osobowych. Dane mogą być udostępniane partnerom logistycznym, platformom płatniczym lub organom tylko gdy jest to konieczne. Możesz żądać dostępu, sprostowania lub usunięcia danych, jeśli ma to zastosowanie.'
  },
  ko: {
    navTerms: '약관', navPrivacy: '개인정보', termsTitle: '서비스 이용약관', privacyTitle: '개인정보 처리방침', updated: '최종 업데이트: 2026년 2월 24일', termsText: 'Rhythm Nexus 서비스를 이용하면 정확한 주문/연락처 정보를 제공하고, 목적지 국가의 통관·세금 규정을 준수하며, 웹사이트를 합법적으로 이용하는 데 동의한 것으로 간주됩니다. 배송 기간은 예상치이며 세관, 우편 사업자, 날씨 또는 당사 통제 밖의 사유로 지연될 수 있습니다. 필수 정보가 누락되었거나 안전한 배송 완료가 불가능한 경우 당사는 주문을 취소하고 환불할 수 있습니다. 본 사이트에 게시된 상품·배송·지원 정책은 본 약관의 일부입니다.', privacyText: '당사는 주문 처리 및 문의 대응을 위해 이름, 이메일, 전화번호, 주문 참조, 목적지 정보, 추적 정보를 수집합니다. 수집된 정보는 주문 이행, 고객 지원, 사기 방지, 법적 준수 및 서비스 개선에 사용됩니다. 당사는 개인정보를 판매하지 않습니다. 서비스 제공 또는 법적 의무 이행에 필요한 경우에만 물류 파트너, 결제 플랫폼, 당국과 정보를 공유할 수 있습니다. 관련 법령에 따라 정보 열람·정정·삭제를 요청할 수 있습니다.'
  },
  no: {
    navTerms: 'Vilkår', navPrivacy: 'Personvern', termsTitle: 'Vilkår for bruk', privacyTitle: 'Personvernerklæring', updated: 'Sist oppdatert: 24. februar 2026', termsText: 'Ved å bruke Rhythm Nexus-tjenester godtar du å oppgi korrekte ordre- og kontaktopplysninger, følge toll- og skatteregler i mottakerlandet, og bruke nettstedet lovlig. Leveringstider er estimater og kan forsinkes av toll, postoperatører, vær eller andre forhold utenfor vår kontroll. Vi kan kansellere og refundere ordre dersom obligatoriske opplysninger mangler eller forsendelsen ikke kan fullføres på en trygg måte. Produkt-, frakt- og supportpolicyer på nettstedet er en del av disse vilkårene.', privacyText: 'Vi samler inn informasjonen som trengs for å behandle ordre og svare på henvendelser, inkludert navn, e-post, telefonnummer, ordrereferanser, destinasjonsdetaljer og sporingsinformasjon. Data brukes til ordreoppfyllelse, kundestøtte, svindelforebygging, lovpålagt etterlevelse og tjenesteforbedring. Vi selger ikke personopplysninger. Data kan deles med logistikkpartnere, betalingsplattformer eller myndigheter kun når det er nødvendig. Du kan be om innsyn, retting eller sletting der dette gjelder.'
  },
  ru: {
    navTerms: 'Условия', navPrivacy: 'Конфиденциальность', termsTitle: 'Условия обслуживания', privacyTitle: 'Политика конфиденциальности', updated: 'Последнее обновление: 24 февраля 2026 г.', termsText: 'Используя сервисы Rhythm Nexus, вы соглашаетесь предоставлять точные данные заказа и контактов, соблюдать таможенные и налоговые правила страны назначения и использовать сайт законно. Сроки доставки являются ориентировочными и могут задерживаться из-за таможни, почтовых операторов, погоды или иных факторов вне нашего контроля. Мы можем отменить заказ и вернуть средства, если отсутствуют обязательные данные или отправка не может быть безопасно завершена. Политики по товарам, доставке и поддержке на этом сайте являются частью данных условий.', privacyText: 'Мы собираем данные, необходимые для обработки заказов и ответов на обращения: имя, e-mail, телефон, сведения о заказе, данные назначения и информацию отслеживания. Эти данные используются для выполнения заказов, поддержки клиентов, предотвращения мошенничества, соблюдения закона и улучшения сервиса. Мы не продаем персональные данные. Данные могут передаваться логистическим партнерам, платежным платформам или органам власти только при необходимости. В применимых случаях вы можете запросить доступ, исправление или удаление ваших персональных данных.'
  },
  sv: {
    navTerms: 'Villkor', navPrivacy: 'Integritet', termsTitle: 'Användarvillkor', privacyTitle: 'Integritetspolicy', updated: 'Senast uppdaterad: 24 februari 2026', termsText: 'Genom att använda Rhythm Nexus tjänster godkänner du att lämna korrekta order- och kontaktuppgifter, följa tull- och skatteregler i destinationslandet och använda webbplatsen lagligt. Leveranstider är uppskattningar och kan försenas av tull, postoperatörer, väder eller andra faktorer utanför vår kontroll. Vi kan annullera och återbetala en order om obligatoriska uppgifter saknas eller om leveransen inte kan slutföras säkert. Produkt-, frakt- och supportpolicyer på denna webbplats är en del av dessa villkor.', privacyText: 'Vi samlar in den information som behövs för orderhantering och kundförfrågningar, inklusive namn, e-post, telefonnummer, orderreferenser, destinationsuppgifter och spårningsinformation. Uppgifterna används för orderuppfyllelse, kundsupport, bedrägeriförebyggande, regelefterlevnad och tjänsteförbättring. Vi säljer inte personuppgifter. Uppgifter kan delas med logistikpartners, betalplattformar eller myndigheter endast när det behövs. Du kan begära tillgång, rättelse eller radering av dina personuppgifter där tillämpligt.'
  },
  fi: {
    navTerms: 'Ehdot', navPrivacy: 'Tietosuoja', termsTitle: 'Käyttöehdot', privacyTitle: 'Tietosuojakäytäntö', updated: 'Viimeksi päivitetty: 24. helmikuuta 2026', termsText: 'Käyttämällä Rhythm Nexusin palveluja sitoudut antamaan oikeat tilaus- ja yhteystiedot, noudattamaan kohdemaan tulli- ja verosääntöjä sekä käyttämään sivustoa lainmukaisesti. Toimitusajat ovat arvioita ja voivat viivästyä tullin, postitoimijoiden, sään tai muiden hallintamme ulkopuolisten syiden vuoksi. Voimme peruuttaa tilauksen ja palauttaa maksun, jos pakollisia tietoja puuttuu tai lähetystä ei voida toteuttaa turvallisesti. Sivustolla julkaistut tuote-, toimitus- ja tukikäytännöt ovat osa näitä ehtoja.', privacyText: 'Keräämme tiedot, joita tarvitaan tilausten käsittelyyn ja yhteydenottoihin vastaamiseen, kuten nimi, sähköposti, puhelinnumero, tilaustiedot, kohdetiedot ja seurantatiedot. Tietoja käytetään tilausten toteutukseen, asiakastukeen, petosten ehkäisyyn, lakisääteisiin velvoitteisiin ja palvelun kehittämiseen. Emme myy henkilötietoja. Tietoja voidaan jakaa logistiikkakumppaneille, maksualustoille tai viranomaisille vain tarvittaessa. Soveltuvin osin voit pyytää tietojen tarkastusta, oikaisua tai poistoa.'
  },
  tl: {
    navTerms: 'Mga Tuntunin', navPrivacy: 'Pribasiya', termsTitle: 'Mga Tuntunin ng Serbisyo', privacyTitle: 'Patakaran sa Pribasiya', updated: 'Huling na-update: 24 Pebrero 2026', termsText: 'Sa paggamit ng mga serbisyo ng Rhythm Nexus, sumasang-ayon kang magbigay ng tamang impormasyon sa order at contact, sumunod sa customs at tax rules ng bansang padadalhan, at gamitin ang website nang ayon sa batas. Tantya lamang ang delivery timeline at maaaring maantala dahil sa customs, postal operators, panahon, o iba pang salik na wala sa aming kontrol. Maaari naming kanselahin at i-refund ang order kung kulang ang kinakailangang detalye o hindi ligtas na maipagpatuloy ang shipment. Bahagi ng mga tuntuning ito ang product, shipping, at support policies na nasa site.', privacyText: 'Kinokolekta namin ang impormasyong kailangan para sa pagproseso ng order at pagsagot sa mga inquiry, kabilang ang pangalan, email, numero ng telepono, order references, destination details, at tracking information. Ginagamit ito para sa order fulfilment, customer support, fraud prevention, legal compliance, at service improvement. Hindi kami nagbebenta ng personal data. Maaaring ibahagi ang data sa logistics partners, payment platforms, o awtoridad kapag kinakailangan lamang. Maaari kang humiling ng access, correction, o deletion ng iyong personal data kung naaangkop.'
  },
  vi: {
    navTerms: 'Điều khoản', navPrivacy: 'Quyền riêng tư', termsTitle: 'Điều khoản dịch vụ', privacyTitle: 'Chính sách quyền riêng tư', updated: 'Cập nhật lần cuối: 24 tháng 2 năm 2026', termsText: 'Khi sử dụng dịch vụ của Rhythm Nexus, bạn đồng ý cung cấp thông tin đơn hàng và liên hệ chính xác, tuân thủ quy định hải quan và thuế của quốc gia đích, và sử dụng website hợp pháp. Thời gian giao hàng chỉ là ước tính và có thể chậm do hải quan, đơn vị bưu chính, thời tiết hoặc các yếu tố ngoài tầm kiểm soát của chúng tôi. Chúng tôi có thể hủy và hoàn tiền đơn hàng nếu thiếu thông tin bắt buộc hoặc không thể hoàn tất vận chuyển an toàn. Các chính sách sản phẩm, vận chuyển và hỗ trợ trên website là một phần của điều khoản này.', privacyText: 'Chúng tôi thu thập thông tin cần thiết để xử lý đơn hàng và phản hồi yêu cầu, bao gồm tên, email, số điện thoại, mã đơn hàng, thông tin điểm đến và dữ liệu theo dõi. Dữ liệu được dùng cho thực hiện đơn hàng, hỗ trợ khách hàng, chống gian lận, tuân thủ pháp luật và cải thiện dịch vụ. Chúng tôi không bán dữ liệu cá nhân. Dữ liệu chỉ được chia sẻ với đối tác logistics, nền tảng thanh toán hoặc cơ quan chức năng khi cần thiết. Bạn có thể yêu cầu truy cập, chỉnh sửa hoặc xóa dữ liệu cá nhân theo quy định áp dụng.'
  },
  cy: {
    navTerms: 'Telerau', navPrivacy: 'Preifatrwydd', termsTitle: 'Telerau Gwasanaeth', privacyTitle: 'Polisi Preifatrwydd', updated: 'Diweddarwyd ddiwethaf: 24 Chwefror 2026', termsText: 'Drwy ddefnyddio gwasanaethau Rhythm Nexus, rydych yn cytuno i ddarparu gwybodaeth archeb a chyswllt gywir, cydymffurfio â rheolau tollau a threthi’r wlad gyrchfan, a defnyddio’r wefan yn gyfreithlon. Mae amserlenni dosbarthu yn amcangyfrifon a gallant gael eu hoedi oherwydd tollau, gweithredwyr post, tywydd neu ffactorau eraill y tu allan i’n rheolaeth. Gallwn ganslo ac ad-dalu archebion os yw manylion gorfodol ar goll neu os na ellir cwblhau’r llwyth yn ddiogel. Mae polisïau cynnyrch, cludo a chymorth ar y wefan yn rhan o’r telerau hyn.', privacyText: 'Rydym yn casglu’r wybodaeth sydd ei hangen i brosesu archebion ac ymateb i ymholiadau, gan gynnwys enw, e-bost, rhif ffôn, cyfeirnodau archeb, manylion cyrchfan a gwybodaeth olrhain. Defnyddir y data hwn ar gyfer cyflawni archebion, cymorth cwsmeriaid, atal twyll, cydymffurfio cyfreithiol a gwella gwasanaeth. Nid ydym yn gwerthu data personol. Gellir rhannu data gyda phartneriaid logisteg, llwyfannau talu neu awdurdodau dim ond pan fo angen. Gallwch ofyn am fynediad, cywiro neu ddileu eich data personol lle bo’n berthnasol.'
  },
  ta: {
    navTerms: 'விதிமுறைகள்', navPrivacy: 'தனியுரிமை', termsTitle: 'சேவை விதிமுறைகள்', privacyTitle: 'தனியுரிமைக் கொள்கை', updated: 'கடைசியாக புதுப்பிக்கப்பட்டது: 24 பிப்ரவரி 2026', termsText: 'Rhythm Nexus சேவைகளை பயன்படுத்துவதன் மூலம், நீங்கள் சரியான ஆர்டர் மற்றும் தொடர்பு தகவல்களை வழங்கவும், இலக்கு நாட்டின் சுங்க/வரி விதிகளை பின்பற்றவும், இணையதளத்தை சட்டபூர்வமாக பயன்படுத்தவும் ஒப்புக்கொள்கிறீர்கள். விநியோக காலம் மதிப்பீடு மட்டுமே; சுங்கம், அஞ்சல் சேவை, வானிலை அல்லது எங்கள் கட்டுப்பாட்டுக்கு வெளியான காரணங்களால் தாமதம் ஏற்படலாம். தேவையான தகவல்கள் இல்லை அல்லது பாதுகாப்பாக அனுப்ப முடியாத நிலை ஏற்பட்டால், ஆர்டரை ரத்து செய்து பணத்தைத் திருப்பியளிக்கலாம். இத்தளத்தில் உள்ள தயாரிப்பு, கப்பல் மற்றும் ஆதரவு கொள்கைகள் இவ்விதிமுறைகளின் பகுதியாகும்.', privacyText: 'ஆர்டர் செயலாக்கம் மற்றும் கேள்விகளுக்குப் பதிலளிக்க தேவையான தகவல்களை—பெயர், மின்னஞ்சல், தொலைபேசி எண், ஆர்டர் குறிப்புகள், இலக்கு விவரங்கள் மற்றும் கண்காணிப்பு தகவல்கள்—நாங்கள் சேகரிக்கிறோம். இத்தகவல்கள் ஆர்டர் நிறைவேற்றம், வாடிக்கையாளர் ஆதரவு, மோசடி தடுப்பு, சட்ட இணக்கம் மற்றும் சேவை மேம்பாட்டிற்குப் பயன்படுத்தப்படுகின்றன. தனிப்பட்ட தரவுகளை நாங்கள் விற்கவில்லை. சேவை வழங்க அல்லது சட்டப் பொறுப்புகளை நிறைவேற்ற தேவையானபோது மட்டுமே லாஜிஸ்டிக்ஸ் கூட்டாளர்கள், கட்டண தளங்கள் அல்லது அதிகாரிகளுடன் பகிரப்படும். பொருந்துமிடத்தில், உங்கள் தரவை அணுக, திருத்த, அல்லது நீக்க கோரலாம்.'
  },
  mi: {
    navTerms: 'Ngā Ture', navPrivacy: 'Tūmataitinga', termsTitle: 'Ngā Ture Ratonga', privacyTitle: 'Kaupapa Here Tūmataiti', updated: 'Whakahoutanga whakamutunga: 24 Hui-tanguru 2026', termsText: 'Mā te whakamahi i ngā ratonga a Rhythm Nexus, ka whakaae koe ki te tuku mōhiohio ota me ngā kōrero whakapā tika, ki te whai i ngā ture tāke me ngā tikanga māngai o te whenua ūnga, ā, ki te whakamahi i te pae tukutuku i raro i te ture. He tatauranga noa ngā wā tuku, ā, ka taea te whakaroa nā te tikanga māngai, ngā kaiwhakarato mēra, te huarere, me ētahi atu take i waho i tō mātou mana. Ka āhei mātou ki te whakakore ota me te whakahoki moni mēnā kāore ngā kōrero e hiahiatia ana i te oti, kāore rānei e taea te whakaoti haumaru i te tuku. Ko ngā kaupapa here hua, tuku me te tautoko kei tēnei pae he wāhanga nō ēnei ture.', privacyText: 'Ka kohikohi mātou i ngā raraunga e hiahiatia ana mō te tukatuka ota me te whakautu pātai, tae atu ki te ingoa, īmēra, nama waea, tohutoro ota, kōrero ūnga, me ngā kōrero aroturuki. Ka whakamahia ēnei raraunga mō te whakatutuki ota, tautoko kiritaki, ārai tinihanga, ū ki te ture, me te whakapai ratonga. Kāore mātou e hoko raraunga whaiaro. Ka taea te tiritiri raraunga ki ngā hoa kawe, papamahi utu, mana whakahaere rānei i te wā e tika ana anake. Ka āhei koe ki te tono uru, whakatika, muku rānei i ō raraunga whaiaro mēnā e hāngai ana.'
  }
};

const POLICY_SUPPLEMENTS = {
  en: {
    termsSupplement: 'You must not misuse the website, attempt unauthorized access, submit fraudulent details, or use automated scraping tools that disrupt services. We may update these terms at any time by posting a revised effective date. VAT registration number: Not applicable. Company business address: Not publicly disclosed. Contact: rhythmnexusco@gmail.com | +65 8835 2089. EU consumers may use the ODR platform: https://ec.europa.eu/consumers/odr/',
    privacySupplement: 'For users in the EU, EEA, and Switzerland, non-essential cookies and personalized advertising technologies are used only after consent is granted through a consent banner, and consent can be changed or withdrawn at any time. Privacy requests can be sent to rhythmnexusco@gmail.com or +65 8835 2089. VAT registration number: Not applicable.'
  },
  de: {
    termsSupplement: 'Sie dürfen die Website nicht missbrauchen, keinen unbefugten Zugriff versuchen, keine betrügerischen Angaben machen und keine automatisierten Scraping-Tools verwenden, die unsere Dienste beeinträchtigen. Wir können diese Bedingungen von Zeit zu Zeit aktualisieren; bei weiterer Nutzung nach einer Aktualisierung gelten die überarbeiteten Bedingungen als akzeptiert.',
    privacySupplement: 'Für Nutzer in der EU, im EWR und in der Schweiz werden nicht notwendige Cookies und personalisierte Werbetechnologien erst nach Einwilligung über ein Consent-Banner verwendet. Sie können Ihre Einwilligung jederzeit widerrufen oder anpassen und gemäß geltendem Datenschutzrecht Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit oder Widerspruch verlangen.'
  },
  fr: {
    termsSupplement: 'Vous ne devez pas détourner le site, tenter un accès non autorisé, soumettre de fausses informations ou utiliser des outils automatisés de scraping qui perturbent le service. Nous pouvons modifier ces conditions; en continuant à utiliser le site après mise à jour, vous acceptez les conditions révisées.',
    privacySupplement: 'Pour les utilisateurs de l’UE, de l’EEE et de la Suisse, les cookies non essentiels et les technologies publicitaires personnalisées ne sont utilisés qu’après consentement via une bannière de consentement. Vous pouvez retirer ou modifier votre consentement à tout moment, et demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou l’opposition selon la législation applicable.'
  },
  es: {
    termsSupplement: 'No debes hacer un uso indebido del sitio, intentar accesos no autorizados, enviar datos fraudulentos ni usar herramientas automáticas de scraping que afecten el servicio. Podemos actualizar estos términos periódicamente; si sigues usando el sitio tras una actualización, aceptas los términos revisados.',
    privacySupplement: 'Para usuarios de la UE, EEE y Suiza, las cookies no esenciales y las tecnologías de publicidad personalizada solo se usan tras obtener consentimiento mediante un banner. Puedes retirar o actualizar tu consentimiento en cualquier momento, y solicitar acceso, rectificación, eliminación, limitación, portabilidad u oposición conforme a la normativa aplicable.'
  },
  ja: {
    termsSupplement: '不正利用、無断アクセスの試行、虚偽情報の送信、サービスを妨害する自動スクレイピングツールの利用は禁止されています。規約は随時更新される場合があり、更新後に利用を継続した場合は改定後の規約に同意したものとみなされます。',
    privacySupplement: 'EU・EEA・スイスのユーザーについては、同意バナーで同意が得られるまで、必須ではないCookieおよびパーソナライズ広告技術は使用しません。同意はいつでも撤回・変更でき、適用法令に基づき、アクセス、訂正、削除、処理制限、データポータビリティ、異議申立ての権利を行使できます。'
  },
  zh: {
    termsSupplement: '您不得滥用本网站、尝试未授权访问、提交虚假信息，或使用影响服务运行的自动抓取工具。我们可能不时更新本条款；更新后继续使用即表示您接受修订后的条款。',
    privacySupplement: '对于欧盟、欧洲经济区及瑞士用户，非必要 Cookie 与个性化广告技术仅在您通过同意横幅授权后才会启用。您可随时撤回或更新同意，并可依据适用数据保护法律行使访问、更正、删除、限制、可携带及反对处理等权利。'
  },
  'zh-hant': {
    termsSupplement: '您不得濫用本網站、嘗試未授權存取、提交不實資料，或使用影響服務運作的自動擷取工具。我們可能不時更新本條款；更新後若您繼續使用，即視為接受修訂後條款。',
    privacySupplement: '針對歐盟、歐洲經濟區與瑞士使用者，非必要 Cookie 與個人化廣告技術僅會在您透過同意橫幅授權後啟用。您可隨時撤回或更新同意，並可依適用資料保護法行使查閱、更正、刪除、限制、可攜與反對處理等權利。'
  },
  pt: {
    termsSupplement: 'Você não deve usar o site de forma abusiva, tentar acesso não autorizado, enviar dados fraudulentos ou usar ferramentas automatizadas de raspagem que prejudiquem o serviço. Podemos atualizar estes termos periodicamente; o uso contínuo após atualização significa aceitação dos termos revisados.',
    privacySupplement: 'Para utilizadores da UE, EEE e Suíça, cookies não essenciais e tecnologias de publicidade personalizada só são usados após consentimento através de banner. Você pode retirar ou atualizar o consentimento a qualquer momento e solicitar acesso, correção, eliminação, restrição, portabilidade ou oposição conforme a lei aplicável.'
  },
  hi: {
    termsSupplement: 'आप वेबसाइट का दुरुपयोग नहीं कर सकते, अनधिकृत पहुँच का प्रयास नहीं कर सकते, धोखाधड़ीपूर्ण जानकारी जमा नहीं कर सकते, और सेवा बाधित करने वाले स्वचालित स्क्रैपिंग टूल का उपयोग नहीं कर सकते। हम समय-समय पर इन शर्तों को अपडेट कर सकते हैं; अपडेट के बाद उपयोग जारी रखने का अर्थ संशोधित शर्तों की स्वीकृति है।',
    privacySupplement: 'EU, EEA और Switzerland के उपयोगकर्ताओं के लिए, गैर-आवश्यक कुकीज़ और वैयक्तिकृत विज्ञापन तकनीकें केवल सहमति बैनर के माध्यम से सहमति मिलने के बाद ही उपयोग की जाती हैं। आप किसी भी समय सहमति वापस ले सकते हैं या बदल सकते हैं, और लागू डेटा संरक्षण कानूनों के तहत एक्सेस, सुधार, हटाने, प्रतिबंध, पोर्टेबिलिटी या आपत्ति के अधिकार का उपयोग कर सकते हैं।'
  },
  th: {
    termsSupplement: 'คุณต้องไม่ใช้เว็บไซต์ในทางที่ผิด พยายามเข้าถึงระบบโดยไม่ได้รับอนุญาต ส่งข้อมูลอันเป็นเท็จ หรือใช้เครื่องมือดึงข้อมูลอัตโนมัติที่รบกวนบริการ เราอาจอัปเดตข้อกำหนดนี้เป็นระยะ และการใช้งานต่อหลังการอัปเดตถือว่าคุณยอมรับข้อกำหนดฉบับแก้ไข',
    privacySupplement: 'สำหรับผู้ใช้ในสหภาพยุโรป EEA และสวิตเซอร์แลนด์ คุกกี้ที่ไม่จำเป็นและเทคโนโลยีโฆษณาแบบปรับให้เหมาะบุคคลจะใช้งานได้ก็ต่อเมื่อได้รับความยินยอมผ่านแบนเนอร์เท่านั้น คุณสามารถเพิกถอนหรือเปลี่ยนแปลงความยินยอมได้ทุกเมื่อ และใช้สิทธิในการเข้าถึง แก้ไข ลบ จำกัดการประมวลผล โอนย้ายข้อมูล หรือคัดค้านตามกฎหมายที่ใช้บังคับ'
  },
  ms: {
    termsSupplement: 'Anda tidak boleh menyalahgunakan laman web, cuba akses tanpa kebenaran, menyerahkan maklumat palsu, atau menggunakan alat scraping automatik yang mengganggu perkhidmatan. Kami boleh mengemas kini terma ini dari semasa ke semasa; penggunaan berterusan selepas kemas kini bermaksud anda menerima terma yang disemak.',
    privacySupplement: 'Bagi pengguna di EU, EEA dan Switzerland, kuki tidak penting dan teknologi iklan diperibadikan hanya digunakan selepas persetujuan diberikan melalui banner persetujuan. Anda boleh menarik balik atau mengemas kini persetujuan pada bila-bila masa, serta meminta akses, pembetulan, pemadaman, sekatan, kebolehportan data atau bantahan di bawah undang-undang perlindungan data yang berkenaan.'
  },
  nl: {
    termsSupplement: 'Je mag de website niet misbruiken, geen ongeautoriseerde toegang proberen te krijgen, geen frauduleuze gegevens indienen en geen geautomatiseerde scrapingtools gebruiken die de dienst verstoren. We kunnen deze voorwaarden periodiek bijwerken; voortgezet gebruik na een update betekent aanvaarding van de herziene voorwaarden.',
    privacySupplement: 'Voor gebruikers in de EU, EER en Zwitserland worden niet-essentiële cookies en gepersonaliseerde advertentietechnologie alleen gebruikt na toestemming via een toestemmingsbanner. Je kunt toestemming op elk moment intrekken of wijzigen en rechten op inzage, correctie, verwijdering, beperking, dataportabiliteit of bezwaar uitoefenen volgens toepasselijk recht.'
  },
  id: {
    termsSupplement: 'Anda tidak boleh menyalahgunakan situs, mencoba akses tanpa izin, mengirim data palsu, atau menggunakan alat scraping otomatis yang mengganggu layanan. Kami dapat memperbarui ketentuan ini dari waktu ke waktu; penggunaan berkelanjutan setelah pembaruan berarti Anda menyetujui ketentuan yang telah direvisi.',
    privacySupplement: 'Untuk pengguna di UE, EEA, dan Swiss, cookie non-esensial serta teknologi iklan yang dipersonalisasi hanya digunakan setelah persetujuan diberikan melalui banner persetujuan. Anda dapat menarik atau memperbarui persetujuan kapan saja, serta meminta akses, perbaikan, penghapusan, pembatasan, portabilitas, atau keberatan sesuai hukum perlindungan data yang berlaku.'
  },
  cs: {
    termsSupplement: 'Nesmíte web zneužívat, pokoušet se o neoprávněný přístup, zadávat podvodné údaje ani používat automatizované scraping nástroje, které narušují služby. Tyto podmínky můžeme průběžně aktualizovat; pokračující používání po aktualizaci znamená souhlas s revidovaným zněním.',
    privacySupplement: 'Pro uživatele v EU, EHP a Švýcarsku používáme neesenciální cookies a personalizované reklamní technologie až po udělení souhlasu prostřednictvím consent banneru. Souhlas můžete kdykoli odvolat nebo upravit a uplatnit práva na přístup, opravu, výmaz, omezení zpracování, přenositelnost či námitku podle příslušných právních předpisů.'
  },
  it: {
    termsSupplement: 'Non devi utilizzare impropriamente il sito, tentare accessi non autorizzati, inviare dati fraudolenti o usare strumenti di scraping automatico che interrompono il servizio. Possiamo aggiornare periodicamente questi termini; l’uso continuato dopo un aggiornamento implica accettazione dei termini revisionati.',
    privacySupplement: 'Per gli utenti in UE, SEE e Svizzera, cookie non essenziali e tecnologie pubblicitarie personalizzate vengono usati solo dopo il consenso tramite banner. Puoi revocare o aggiornare il consenso in qualsiasi momento e richiedere accesso, rettifica, cancellazione, limitazione, portabilità o opposizione ai sensi delle leggi applicabili.'
  },
  he: {
    termsSupplement: 'אין לעשות שימוש לרעה באתר, לנסות גישה לא מורשית, למסור פרטים כוזבים או להשתמש בכלי סקרייפינג אוטומטיים שמפריעים לשירות. אנו רשאים לעדכן תנאים אלה מעת לעת; המשך שימוש לאחר עדכון מהווה הסכמה לתנאים המעודכנים.',
    privacySupplement: 'למשתמשים באיחוד האירופי, באזור הכלכלי האירופי ובשוויץ, קובצי Cookie לא חיוניים וטכנולוגיות פרסום מותאם אישית מופעלים רק לאחר מתן הסכמה באמצעות באנר הסכמה. ניתן לבטל או לעדכן הסכמה בכל עת, ולממש זכויות גישה, תיקון, מחיקה, הגבלה, ניידות נתונים או התנגדות לפי הדין החל.'
  },
  ga: {
    termsSupplement: 'Ní ceadmhach duit an suíomh a mhí-úsáid, rochtain neamhúdaraithe a thriail, sonraí calaoiseacha a chur isteach, ná uirlisí scraping uathoibrithe a úsáid a chuireann isteach ar sheirbhísí. Féadfaimid na téarmaí seo a nuashonrú ó am go chéile; ciallaíonn úsáid leanúnach tar éis nuashonraithe go nglacann tú leis na téarmaí leasaithe.',
    privacySupplement: 'Do úsáideoirí san AE, sa LEE agus san Eilvéis, úsáidtear fianáin neamhriachtanacha agus teicneolaíochtaí fógraíochta pearsantaithe ach amháin tar éis toiliú trí bhanner toilithe. Is féidir leat toiliú a tharraingt siar nó a nuashonrú am ar bith, agus cearta rochtana, ceartaithe, scriosta, srianta, iniomparthachta nó agóide a fheidhmiú faoi dhlíthe cosanta sonraí is infheidhme.'
  },
  pl: {
    termsSupplement: 'Nie wolno nadużywać witryny, próbować nieuprawnionego dostępu, podawać fałszywych danych ani używać automatycznych narzędzi scrapingowych zakłócających działanie usług. Możemy okresowo aktualizować niniejsze warunki; dalsze korzystanie po aktualizacji oznacza akceptację wersji zmienionej.',
    privacySupplement: 'Dla użytkowników z UE, EOG i Szwajcarii niezbędne i spersonalizowane technologie reklamowe są uruchamiane dopiero po wyrażeniu zgody przez baner zgody. Zgodę można w każdej chwili wycofać lub zmienić oraz skorzystać z praw dostępu, sprostowania, usunięcia, ograniczenia, przenoszenia danych lub sprzeciwu zgodnie z właściwymi przepisami.'
  },
  ko: {
    termsSupplement: '웹사이트를 오용하거나, 무단 접근을 시도하거나, 허위 정보를 제출하거나, 서비스 운영을 방해하는 자동 스크래핑 도구를 사용해서는 안 됩니다. 당사는 본 약관을 수시로 업데이트할 수 있으며, 업데이트 후 계속 이용하면 개정 약관에 동의한 것으로 간주됩니다.',
    privacySupplement: 'EU, EEA, 스위스 사용자에 대해서는 동의 배너를 통해 동의가 확인된 후에만 비필수 쿠키 및 맞춤형 광고 기술을 사용합니다. 사용자는 언제든지 동의를 철회·변경할 수 있으며, 관련 법령에 따라 열람, 정정, 삭제, 처리 제한, 이동권, 처리 반대 권리를 행사할 수 있습니다.'
  },
  no: {
    termsSupplement: 'Du må ikke misbruke nettstedet, forsøke uautorisert tilgang, sende inn falske opplysninger eller bruke automatiserte scraping-verktøy som forstyrrer tjenestene. Vi kan oppdatere disse vilkårene fra tid til annen; fortsatt bruk etter oppdatering betyr at du godtar de reviderte vilkårene.',
    privacySupplement: 'For brukere i EU, EØS og Sveits brukes ikke-essensielle informasjonskapsler og personlige annonseringsteknologier kun etter samtykke via samtykkebanner. Du kan når som helst trekke tilbake eller endre samtykke, og be om innsyn, retting, sletting, begrensning, dataportabilitet eller protest i tråd med gjeldende personvernlovgivning.'
  },
  ru: {
    termsSupplement: 'Запрещается злоупотреблять сайтом, пытаться получить несанкционированный доступ, предоставлять мошеннические сведения или использовать автоматизированные инструменты скрейпинга, нарушающие работу сервиса. Мы можем периодически обновлять эти условия; продолжение использования после обновления означает согласие с новой редакцией.',
    privacySupplement: 'Для пользователей из ЕС, ЕЭЗ и Швейцарии несущественные cookie и технологии персонализированной рекламы используются только после согласия через баннер согласия. Вы можете в любое время отозвать или изменить согласие, а также реализовать права на доступ, исправление, удаление, ограничение обработки, переносимость данных и возражение в соответствии с применимым законодательством.'
  },
  sv: {
    termsSupplement: 'Du får inte missbruka webbplatsen, försöka få obehörig åtkomst, lämna bedrägliga uppgifter eller använda automatiserade scraping-verktyg som stör tjänsterna. Vi kan uppdatera dessa villkor då och då; fortsatt användning efter uppdatering innebär att du accepterar de reviderade villkoren.',
    privacySupplement: 'För användare i EU, EES och Schweiz används icke-nödvändiga cookies och teknik för personanpassad annonsering endast efter samtycke via en samtyckesbanner. Du kan när som helst återkalla eller ändra samtycke och begära tillgång, rättelse, radering, begränsning, dataportabilitet eller invändning enligt tillämplig dataskyddslagstiftning.'
  },
  fi: {
    termsSupplement: 'Et saa käyttää sivustoa väärin, yrittää luvatonta pääsyä, toimittaa vilpillisiä tietoja tai käyttää automaattisia scraping-työkaluja, jotka häiritsevät palvelua. Voimme päivittää näitä ehtoja ajoittain; palvelun käytön jatkaminen päivityksen jälkeen tarkoittaa päivitettyjen ehtojen hyväksymistä.',
    privacySupplement: 'EU-, ETA- ja Sveitsi-käyttäjille ei-välttämättömiä evästeitä ja personoidun mainonnan teknologioita käytetään vasta suostumuksen jälkeen suostumusbannerin kautta. Voit peruuttaa tai päivittää suostumuksen milloin tahansa sekä pyytää pääsyä tietoihin, oikaisua, poistamista, käsittelyn rajoittamista, siirrettävyyttä tai vastustamista sovellettavan tietosuojalainsäädännön mukaisesti.'
  },
  tl: {
    termsSupplement: 'Hindi mo dapat abusuhin ang website, subukang pumasok nang walang pahintulot, magsumite ng mapanlinlang na detalye, o gumamit ng automated scraping tools na nakakaabala sa serbisyo. Maaari naming i-update ang mga tuntuning ito paminsan-minsan; ang patuloy na paggamit matapos ang update ay nangangahulugang tinatanggap mo ang binagong tuntunin.',
    privacySupplement: 'Para sa mga user sa EU, EEA, at Switzerland, ginagamit lamang ang non-essential cookies at personalized advertising technologies pagkatapos ng pahintulot sa consent banner. Maaari mong bawiin o baguhin ang pahintulot anumang oras, at maaari kang humiling ng access, correction, deletion, restriction, portability, o objection rights alinsunod sa naaangkop na data protection laws.'
  },
  vi: {
    termsSupplement: 'Bạn không được lạm dụng website, cố gắng truy cập trái phép, cung cấp thông tin gian lận, hoặc dùng công cụ scraping tự động gây gián đoạn dịch vụ. Chúng tôi có thể cập nhật điều khoản theo thời gian; việc tiếp tục sử dụng sau khi cập nhật đồng nghĩa với việc bạn chấp nhận điều khoản đã sửa đổi.',
    privacySupplement: 'Đối với người dùng tại EU, EEA và Thụy Sĩ, cookie không thiết yếu và công nghệ quảng cáo cá nhân hóa chỉ được sử dụng sau khi có sự đồng ý thông qua banner đồng ý. Bạn có thể rút lại hoặc cập nhật sự đồng ý bất cứ lúc nào, đồng thời yêu cầu quyền truy cập, chỉnh sửa, xóa, hạn chế xử lý, chuyển dữ liệu hoặc phản đối theo luật bảo vệ dữ liệu hiện hành.'
  },
  cy: {
    termsSupplement: 'Ni ddylech gamddefnyddio’r wefan, ceisio mynediad heb awdurdod, cyflwyno manylion twyllodrus, na defnyddio offer scraping awtomataidd sy’n tarfu ar y gwasanaethau. Gallwn ddiweddaru’r telerau hyn o bryd i’w gilydd; mae defnydd parhaus ar ôl diweddariad yn golygu eich bod yn derbyn y telerau diwygiedig.',
    privacySupplement: 'I ddefnyddwyr yn yr UE, yr AEE a’r Swistir, dim ond ar ôl caniatâd drwy faner caniatâd y defnyddir cwcis nad ydynt yn hanfodol a thechnolegau hysbysebu personol. Gallwch dynnu’n ôl neu ddiweddaru caniatâd unrhyw bryd, a gwneud cais am hawliau mynediad, cywiro, dileu, cyfyngu, cludadwyedd data neu wrthwynebu yn unol â’r gyfraith berthnasol.'
  },
  ta: {
    termsSupplement: 'நீங்கள் இணையதளத்தை தவறாக பயன்படுத்தக்கூடாது, அனுமதியற்ற அணுகலை முயற்சிக்கக்கூடாது, போலியான தகவல்களை சமர்ப்பிக்கக்கூடாது, அல்லது சேவையை பாதிக்கும் தானியங்கி scraping கருவிகளை பயன்படுத்தக்கூடாது. இவ்விதிமுறைகளை நாம் காலம் காலமாக புதுப்பிக்கலாம்; புதுப்பிப்புக்குப் பிறகும் சேவையைத் தொடர்ந்துப் பயன்படுத்துவது திருத்தப்பட்ட விதிமுறைகளை ஏற்றுக்கொண்டதாக கருதப்படும்.',
    privacySupplement: 'EU, EEA மற்றும் Switzerland பகுதிகளில் உள்ள பயனர்களுக்கு, அவசியமற்ற cookies மற்றும் தனிப்பயன் விளம்பர தொழில்நுட்பங்கள் consent banner மூலம் ஒப்புதல் கிடைத்த பின்னரே பயன்படுத்தப்படும். நீங்கள் எப்போது வேண்டுமானாலும் ஒப்புதலை திரும்பப் பெறலாம் அல்லது மாற்றலாம், மேலும் பொருந்தும் தரவு பாதுகாப்புச் சட்டங்களின் கீழ் அணுகல், திருத்தம், நீக்கம், கட்டுப்பாடு, தரவு மாற்று உரிமை அல்லது எதிர்ப்பு உரிமைகளை பயன்படுத்தலாம்.'
  },
  mi: {
    termsSupplement: 'Kaua e whakamahi hē i te paetukutuku, e ngana rānei ki te uru kāore i whakaaetia, e tuku kōrero tinihanga, e whakamahi rānei i ngā taputapu scraping aunoa e whakararuraru ana i ngā ratonga. Ka taea e mātou te whakahou i ēnei ture i ētahi wā; ko te whakamahi tonu i muri i te whakahou he tohu whakaae ki ngā ture kua whakahoungia.',
    privacySupplement: 'Mō ngā kaiwhakamahi i te EU, EEA me Huiterangi, ka whakamahia ngā pihikete kāore e tino hiahiatia ana me ngā hangarau pānuitanga whaiaro anake i muri i te whakaaetanga mā te kara whakaae. Ka taea e koe te whakakore, te whakahou rānei i te whakaaetanga i ngā wā katoa, ā, te tono hoki i ngā motika uru, whakatika, muku, here, kawe raraunga, whakahē rānei i raro i ngā ture tiaki raraunga e hāngai ana.'
  }
};

const normalizeLang = (language) => {
  const code = (language || 'en').toLowerCase();
  if (code === 'iw') return 'he';
  if (code === 'fil') return 'tl';
  if (code === 'zh-cn' || code === 'zh-hans') return 'zh';
  if (code === 'zh-tw' || code === 'zh-hk' || code === 'zh-hant') return 'zh-hant';
  if (code.startsWith('nb') || code.startsWith('nn')) return 'no';
  return code;
};

export const policyText = (language) => {
  const lang = normalizeLang(language);
  const translation = POLICY_TRANSLATIONS[lang];
  const supplement = POLICY_SUPPLEMENTS[lang];

  if (!translation || !supplement) {
    throw new Error(`Missing policy translation pack for language: ${lang}`);
  }

  return {
    ...translation,
    ...supplement,
    companyName: COMPANY_NAME,
    contactEmail: COMPANY_EMAIL,
    contactPhone: COMPANY_PHONE,
    vatStatus: 'Not applicable',
  };
};
