'use client';

import React from "react";
import { useRouter } from "next/navigation";
import "../../../App.css";
import { useLanguage } from "../../../LanguageContext";
import { Navigation } from "../../../components/Navigation";

function BackButton() {
  const { t } = useLanguage();
  const router = useRouter();
  return (
    <button
      onClick={() => router.back()}
      className="back-button"
    >
      <span>&larr;</span> {t('backButton')}
    </button>
  );
}

const BlogPageLayout = ({ children }) => {
  const { t } = useLanguage();
  return (
    <>
      <Navigation />
      <div className="container mt-5">
        <BackButton />
        <div className="blog-content-card">
          {children}
        </div>
        <p className="text-muted">© {new Date().getFullYear()} Rhythm Nexus. {t('copyrightText')}</p>
      </div>
    </>
  );
};

const BLOG_PHONE_REQUIREMENT_I18N = {
  en: {
    title: 'Phone Number Required for Shipping (Important)',
    intro: 'For certain destinations, a valid recipient phone number is mandatory for Etsy shipments. This helps customs clearance, VAT/tax coordination, and final-mile delivery communication.',
    requiredTitle: 'Required Countries',
    requiredCountries: ['United States', 'European Union countries (listed below)', 'United Kingdom', 'Norway', 'Switzerland', 'China', 'India', 'Indonesia', 'Philippines', 'South Korea', 'Taiwan', 'Vietnam'],
    euTitle: 'European Union Countries',
    euCountries: 'Austria, Belgium, Czechia, Finland, France, Germany, Ireland, Italy, Netherlands, Poland, Portugal, Spain, Sweden.',
    recommendedTitle: 'Recommended (but not required)',
    recommendedCountries: 'Australia, New Zealand, Canada.',
    whyTitle: 'Why a Phone Number Is Required',
    whyUS: 'United States: Under current tariff handling for postal shipments, recipient contact details may be required for DDP/customs and delivery communication.',
    whyEU: 'European Union: IOSS VAT procedures can require recipient contact details for VAT processing and delivery coordination.',
    whyUK: 'United Kingdom, Switzerland, Norway: VAT/customs collection procedures may require buyer contact for clarification.',
    whyStrict: 'China, India, Indonesia, Philippines, South Korea, Taiwan, Vietnam: strict customs jurisdictions may request recipient phone details to verify declarations or resolve shipment issues.',
    closing: 'Providing a valid recipient phone number helps prevent customs delays, failed delivery attempts, and parcel returns. Customs or local courier/postal services may contact the recipient to clarify declaration details, import information, duties/taxes, required documents, address details, or delivery timing.',
    importantLabel: 'Important:',
    important: 'Missing recipient phone number may result in shipment delays, return-to-sender outcomes, or order cancellation depending on destination-country processing rules.',
  },
  zh: {
    title: '发货需提供电话号码（重要）', intro: '部分目的地的 Etsy 订单必须提供有效收件人电话号码。这有助于清关、VAT/税务处理及末端配送联系。', requiredTitle: '必须提供的国家/地区', requiredCountries: ['美国', '欧盟国家（见下方）', '英国', '挪威', '瑞士', '中国', '印度', '印度尼西亚', '菲律宾', '韩国', '台湾', '越南'], euTitle: '欧盟国家', euCountries: '奥地利、比利时、捷克、芬兰、法国、德国、爱尔兰、意大利、荷兰、波兰、葡萄牙、西班牙、瑞典。', recommendedTitle: '建议提供（但非强制）', recommendedCountries: '澳大利亚、新西兰、加拿大。', whyTitle: '为何需要电话号码', whyUS: '美国：根据当前邮政关税处理要求，DDP/清关与派送联络可能需要收件人联系方式。', whyEU: '欧盟：IOSS VAT 流程可能要求收件人联系方式，以便 VAT 处理和配送协调。', whyUK: '英国、瑞士、挪威：VAT/海关征收流程可能需要联系买家进行补充说明。', whyStrict: '中国、印度、印尼、菲律宾、韩国、台湾、越南：海关要求较严格，可能要求收件人电话用于核验申报或处理异常。', closing: '提供有效电话号码可减少清关延误、派送失败和退件。海关或当地邮政/快递可能会联系收件人确认申报、税费、文件、地址或派送时段。', importantLabel: '重要：', important: '未提供收件人电话号码可能导致延误、退回寄件方或订单取消（取决于目的地处理规则）。' },
  'zh-hant': {
    title: '出貨需提供電話號碼（重要）', intro: '部分目的地的 Etsy 訂單必須提供有效收件人電話號碼。這有助於清關、VAT/稅務處理與末端配送聯絡。', requiredTitle: '必須提供的國家/地區', requiredCountries: ['美國', '歐盟國家（如下）', '英國', '挪威', '瑞士', '中國', '印度', '印尼', '菲律賓', '韓國', '台灣', '越南'], euTitle: '歐盟國家', euCountries: '奧地利、比利時、捷克、芬蘭、法國、德國、愛爾蘭、義大利、荷蘭、波蘭、葡萄牙、西班牙、瑞典。', recommendedTitle: '建議提供（非強制）', recommendedCountries: '澳洲、紐西蘭、加拿大。', whyTitle: '為何需要電話號碼', whyUS: '美國：依目前郵政關稅處理規範，DDP/清關與配送聯絡可能需要收件人聯絡方式。', whyEU: '歐盟：IOSS VAT 流程可能要求收件人聯絡方式，以便 VAT 處理與配送協調。', whyUK: '英國、瑞士、挪威：VAT/海關徵收流程可能需要聯絡買家補充說明。', whyStrict: '中國、印度、印尼、菲律賓、韓國、台灣、越南：海關要求較嚴格，可能要求收件人電話以核驗申報或處理異常。', closing: '提供有效電話可降低清關延誤、配送失敗與退件。海關或當地郵政/快遞可能聯絡收件人確認申報、稅費、文件、地址或配送時段。', importantLabel: '重要：', important: '未提供收件人電話可能導致延誤、退回寄件方或訂單取消（依目的地規則）。' },
  cs: { title: 'Telefonní číslo pro dopravu je povinné (Důležité)', intro: 'Pro některé destinace je u Etsy zásilek povinné platné telefonní číslo příjemce. Pomáhá to s clem, DPH a doručením.', requiredTitle: 'Povinné země', requiredCountries: ['USA', 'země EU (viz níže)', 'Spojené království', 'Norsko', 'Švýcarsko', 'Čína', 'Indie', 'Indonésie', 'Filipíny', 'Jižní Korea', 'Tchaj-wan', 'Vietnam'], euTitle: 'Země Evropské unie', euCountries: 'Rakousko, Belgie, Česko, Finsko, Francie, Německo, Irsko, Itálie, Nizozemsko, Polsko, Portugalsko, Španělsko, Švédsko.', recommendedTitle: 'Doporučeno (není povinné)', recommendedCountries: 'Austrálie, Nový Zéland, Kanada.', whyTitle: 'Proč je telefonní číslo vyžadováno', whyUS: 'USA: V rámci aktuálních celních pravidel pro poštovní zásilky může být kontakt příjemce vyžadován pro DDP/clo a doručení.', whyEU: 'EU: Proces IOSS DPH může vyžadovat kontakt příjemce pro zpracování DPH a koordinaci doručení.', whyUK: 'Spojené království, Švýcarsko, Norsko: Postupy DPH/clo mohou vyžadovat kontakt kupujícího pro upřesnění.', whyStrict: 'Čína, Indie, Indonésie, Filipíny, Jižní Korea, Tchaj-wan, Vietnam: Přísné celní režimy mohou vyžadovat telefon příjemce k ověření deklarací.', closing: 'Platné číslo pomáhá předcházet zpožděním, neúspěšnému doručení a vrácení zásilky. Celní úřad nebo místní dopravce může kontaktovat příjemce kvůli doplnění údajů.', importantLabel: 'Důležité:', important: 'Chybějící telefon příjemce může vést ke zpoždění, vrácení odesílateli nebo zrušení objednávky.' },
  nl: { title: 'Telefoonnummer vereist voor verzending (Belangrijk)', intro: 'Voor bepaalde bestemmingen is een geldig telefoonnummer van de ontvanger verplicht voor Etsy-zendingen. Dit helpt bij douane, btw en bezorging.', requiredTitle: 'Vereiste landen', requiredCountries: ['Verenigde Staten', 'EU-landen (hieronder)', 'Verenigd Koninkrijk', 'Noorwegen', 'Zwitserland', 'China', 'India', 'Indonesië', 'Filipijnen', 'Zuid-Korea', 'Taiwan', 'Vietnam'], euTitle: 'Landen van de Europese Unie', euCountries: 'Oostenrijk, België, Tsjechië, Finland, Frankrijk, Duitsland, Ierland, Italië, Nederland, Polen, Portugal, Spanje, Zweden.', recommendedTitle: 'Aanbevolen (niet verplicht)', recommendedCountries: 'Australië, Nieuw-Zeeland, Canada.', whyTitle: 'Waarom een telefoonnummer vereist is', whyUS: 'Verenigde Staten: Volgens huidige tariefafhandeling voor postzendingen kan contactinformatie van de ontvanger nodig zijn voor DDP/douane en bezorging.', whyEU: 'Europese Unie: IOSS-btw-procedures kunnen ontvangercontact vereisen voor btw-verwerking en bezorgcoördinatie.', whyUK: 'Verenigd Koninkrijk, Zwitserland, Noorwegen: Btw-/douaneprocedures kunnen contact met de koper vereisen voor verduidelijking.', whyStrict: 'China, India, Indonesië, Filipijnen, Zuid-Korea, Taiwan, Vietnam: Strenge douanejurisdicties kunnen ontvangertelefoon opvragen om declaraties te verifiëren.', closing: 'Een geldig nummer helpt vertragingen, mislukte bezorgpogingen en retouren te voorkomen. Douane of lokale vervoerder kan de ontvanger contacteren voor extra informatie.', importantLabel: 'Belangrijk:', important: 'Zonder ontvangernummer kan de zending vertragen, retour gaan of de bestelling geannuleerd worden.' },
  fi: { title: 'Puhelinnumero vaaditaan toimitukseen (Tärkeää)', intro: 'Joihinkin kohdemaihin Etsy-lähetyksissä vaaditaan vastaanottajan voimassa oleva puhelinnumero. Tämä auttaa tullissa, ALV:ssa ja toimituksessa.', requiredTitle: 'Pakolliset maat', requiredCountries: ['Yhdysvallat', 'EU-maat (alla)', 'Yhdistynyt kuningaskunta', 'Norja', 'Sveitsi', 'Kiina', 'Intia', 'Indonesia', 'Filippiinit', 'Etelä-Korea', 'Taiwan', 'Vietnam'], euTitle: 'Euroopan unionin maat', euCountries: 'Itävalta, Belgia, Tšekki, Suomi, Ranska, Saksa, Irlanti, Italia, Alankomaat, Puola, Portugali, Espanja, Ruotsi.', recommendedTitle: 'Suositellaan (ei pakollinen)', recommendedCountries: 'Australia, Uusi-Seelanti, Kanada.', whyTitle: 'Miksi puhelinnumero vaaditaan', whyUS: 'Yhdysvallat: Nykyisten postilähetysten tariffisääntöjen mukaan vastaanottajan yhteystietoja voidaan vaatia DDP/tullia ja toimitusta varten.', whyEU: 'EU: IOSS-ALV-menettelyt voivat vaatia vastaanottajan yhteystiedot ALV-käsittelyyn ja toimituksen koordinointiin.', whyUK: 'Yhdistynyt kuningaskunta, Sveitsi, Norja: ALV-/tullimenettelyt voivat vaatia ostajan yhteydenottoa selvennyksiä varten.', whyStrict: 'Kiina, Intia, Indonesia, Filippiinit, Etelä-Korea, Taiwan, Vietnam: tiukat tullijärjestelmät voivat pyytää vastaanottajan numeroa deklarointien varmistamiseksi.', closing: 'Voimassa oleva numero auttaa ehkäisemään viiveitä, epäonnistuneita toimituksia ja palautuksia. Tulli tai paikallinen kuljetusyhtiö voi ottaa yhteyttä lisätietoja varten.', importantLabel: 'Tärkeää:', important: 'Vastaanottajan numeron puuttuminen voi johtaa viiveisiin, palautukseen lähettäjälle tai tilauksen peruutukseen.' },
  fr: { title: 'Numéro de téléphone requis pour l’expédition (Important)', intro: 'Pour certaines destinations, un numéro valide du destinataire est obligatoire pour les envois Etsy. Cela aide pour la douane, la TVA et la livraison finale.', requiredTitle: 'Pays obligatoires', requiredCountries: ['États-Unis', 'pays de l’Union européenne (ci-dessous)', 'Royaume-Uni', 'Norvège', 'Suisse', 'Chine', 'Inde', 'Indonésie', 'Philippines', 'Corée du Sud', 'Taïwan', 'Vietnam'], euTitle: 'Pays de l’Union européenne', euCountries: 'Autriche, Belgique, Tchéquie, Finlande, France, Allemagne, Irlande, Italie, Pays-Bas, Pologne, Portugal, Espagne, Suède.', recommendedTitle: 'Recommandé (non obligatoire)', recommendedCountries: 'Australie, Nouvelle-Zélande, Canada.', whyTitle: 'Pourquoi un numéro est requis', whyUS: 'États-Unis : selon les règles tarifaires actuelles pour les envois postaux, les coordonnées du destinataire peuvent être requises pour DDP/douane et livraison.', whyEU: 'Union européenne : les procédures IOSS TVA peuvent exiger les coordonnées du destinataire pour le traitement TVA et la coordination de livraison.', whyUK: 'Royaume-Uni, Suisse, Norvège : les procédures TVA/douane peuvent nécessiter le contact de l’acheteur pour clarification.', whyStrict: 'Chine, Inde, Indonésie, Philippines, Corée du Sud, Taïwan, Vietnam : juridictions douanières strictes pouvant demander le téléphone du destinataire pour vérifier les déclarations.', closing: 'Un numéro valide aide à éviter retards, échecs de livraison et retours. Les douanes ou le transporteur local peuvent contacter le destinataire pour clarifier des informations.', importantLabel: 'Important :', important: 'L’absence du numéro du destinataire peut entraîner un retard, un retour expéditeur ou l’annulation de la commande.' },
  de: { title: 'Telefonnummer für Versand erforderlich (Wichtig)', intro: 'Für bestimmte Ziele ist bei Etsy-Sendungen eine gültige Empfängernummer verpflichtend. Das hilft bei Zoll, MwSt. und Zustellung.', requiredTitle: 'Pflichtländer', requiredCountries: ['Vereinigte Staaten', 'EU-Länder (siehe unten)', 'Vereinigtes Königreich', 'Norwegen', 'Schweiz', 'China', 'Indien', 'Indonesien', 'Philippinen', 'Südkorea', 'Taiwan', 'Vietnam'], euTitle: 'Länder der Europäischen Union', euCountries: 'Österreich, Belgien, Tschechien, Finnland, Frankreich, Deutschland, Irland, Italien, Niederlande, Polen, Portugal, Spanien, Schweden.', recommendedTitle: 'Empfohlen (nicht verpflichtend)', recommendedCountries: 'Australien, Neuseeland, Kanada.', whyTitle: 'Warum eine Telefonnummer erforderlich ist', whyUS: 'USA: Nach aktuellen Tarifregeln für Postsendungen können Empfängerkontaktdaten für DDP/Zoll und Zustellung erforderlich sein.', whyEU: 'EU: IOSS-MwSt.-Verfahren können Empfängerkontaktdaten für MwSt.-Bearbeitung und Lieferkoordination verlangen.', whyUK: 'Vereinigtes Königreich, Schweiz, Norwegen: MwSt.-/Zollverfahren können Rückfragen beim Käufer erfordern.', whyStrict: 'China, Indien, Indonesien, Philippinen, Südkorea, Taiwan, Vietnam: Strenge Zollvorgaben können die Empfängernummer zur Verifikation verlangen.', closing: 'Eine gültige Nummer hilft, Verzögerungen, fehlgeschlagene Zustellungen und Rücksendungen zu vermeiden. Zoll oder lokaler Zusteller kann den Empfänger kontaktieren.', importantLabel: 'Wichtig:', important: 'Fehlt die Empfängernummer, kann es zu Verzögerung, Rücksendung oder Stornierung kommen.' },
  he: { title: 'נדרש מספר טלפון למשלוח (חשוב)', intro: 'ליעדים מסוימים, בהזמנות Etsy נדרש מספר טלפון תקין של הנמען. זה מסייע במכס, במע"מ ובמסירה.', requiredTitle: 'מדינות חובה', requiredCountries: ['ארצות הברית', 'מדינות האיחוד האירופי (למטה)', 'בריטניה', 'נורווגיה', 'שווייץ', 'סין', 'הודו', 'אינדונזיה', 'פיליפינים', 'דרום קוריאה', 'טייוואן', 'וייטנאם'], euTitle: 'מדינות האיחוד האירופי', euCountries: 'אוסטריה, בלגיה, צ׳כיה, פינלנד, צרפת, גרמניה, אירלנד, איטליה, הולנד, פולין, פורטוגל, ספרד, שוודיה.', recommendedTitle: 'מומלץ (לא חובה)', recommendedCountries: 'אוסטרליה, ניו זילנד, קנדה.', whyTitle: 'למה נדרש מספר טלפון', whyUS: 'ארה״ב: לפי כללי תעריפים נוכחיים למשלוחי דואר, ייתכן שיידרשו פרטי קשר של הנמען עבור DDP/מכס ותיאום מסירה.', whyEU: 'האיחוד האירופי: נהלי IOSS במע״מ עשויים לדרוש פרטי קשר של הנמען לעיבוד מע״מ ותיאום מסירה.', whyUK: 'בריטניה, שווייץ, נורווגיה: נהלי מע״מ/מכס עשויים לדרוש יצירת קשר עם הקונה להבהרות.', whyStrict: 'סין, הודו, אינדונזיה, פיליפינים, דרום קוריאה, טייוואן, וייטנאם: תחומי מכס מחמירים שעשויים לדרוש מספר נמען לאימות הצהרות.', closing: 'מספר תקין מסייע למנוע עיכובים, כשלי מסירה והחזרות. המכס או חברת משלוחים מקומית עשויים ליצור קשר עם הנמען לבירורים.', importantLabel: 'חשוב:', important: 'ללא מספר נמען עלולים להתרחש עיכוב, החזרה לשולח או ביטול הזמנה.' },
  hi: { title: 'शिपिंग के लिए फोन नंबर आवश्यक (महत्वपूर्ण)', intro: 'कुछ गंतव्यों के लिए Etsy शिपमेंट में प्राप्तकर्ता का वैध फोन नंबर अनिवार्य है। इससे कस्टम, VAT/टैक्स और डिलीवरी समन्वय में मदद मिलती है।', requiredTitle: 'अनिवार्य देश', requiredCountries: ['संयुक्त राज्य अमेरिका', 'यूरोपीय संघ देश (नीचे)', 'यूनाइटेड किंगडम', 'नॉर्वे', 'स्विट्ज़रलैंड', 'चीन', 'भारत', 'इंडोनेशिया', 'फिलीपींस', 'दक्षिण कोरिया', 'ताइवान', 'वियतनाम'], euTitle: 'यूरोपीय संघ देश', euCountries: 'ऑस्ट्रिया, बेल्जियम, चेकिया, फिनलैंड, फ्रांस, जर्मनी, आयरलैंड, इटली, नीदरलैंड, पोलैंड, पुर्तगाल, स्पेन, स्वीडन।', recommendedTitle: 'अनुशंसित (पर अनिवार्य नहीं)', recommendedCountries: 'ऑस्ट्रेलिया, न्यूज़ीलैंड, कनाडा।', whyTitle: 'फोन नंबर क्यों आवश्यक है', whyUS: 'अमेरिका: वर्तमान टैरिफ नियमों के तहत पोस्टल शिपमेंट के लिए DDP/कस्टम और डिलीवरी संपर्क हेतु प्राप्तकर्ता जानकारी आवश्यक हो सकती है।', whyEU: 'यूरोपीय संघ: IOSS VAT प्रक्रियाओं में VAT प्रोसेसिंग और डिलीवरी समन्वय हेतु प्राप्तकर्ता संपर्क आवश्यक हो सकता है।', whyUK: 'यूके, स्विट्ज़रलैंड, नॉर्वे: VAT/कस्टम प्रक्रियाओं में स्पष्टीकरण हेतु खरीदार से संपर्क आवश्यक हो सकता है।', whyStrict: 'चीन, भारत, इंडोनेशिया, फिलीपींस, दक्षिण कोरिया, ताइवान, वियतनाम: सख्त कस्टम क्षेत्रों में घोषणा सत्यापन हेतु फोन मांगा जा सकता है।', closing: 'वैध नंबर से देरी, असफल डिलीवरी प्रयास और रिटर्न कम होते हैं। कस्टम या स्थानीय कूरियर अतिरिक्त विवरण के लिए संपर्क कर सकते हैं।', importantLabel: 'महत्वपूर्ण:', important: 'प्राप्तकर्ता फोन नंबर न होने पर देरी, रिटर्न-टू-सेंडर या ऑर्डर रद्द हो सकता है।' },
  id: { title: 'Nomor Telepon Wajib untuk Pengiriman (Penting)', intro: 'Untuk tujuan tertentu, nomor telepon penerima yang valid wajib untuk kiriman Etsy. Ini membantu proses bea cukai, VAT/pajak, dan komunikasi pengiriman.', requiredTitle: 'Negara yang Wajib', requiredCountries: ['Amerika Serikat', 'negara Uni Eropa (di bawah)', 'Inggris', 'Norwegia', 'Swiss', 'Tiongkok', 'India', 'Indonesia', 'Filipina', 'Korea Selatan', 'Taiwan', 'Vietnam'], euTitle: 'Negara Uni Eropa', euCountries: 'Austria, Belgia, Ceko, Finlandia, Prancis, Jerman, Irlandia, Italia, Belanda, Polandia, Portugal, Spanyol, Swedia.', recommendedTitle: 'Disarankan (namun tidak wajib)', recommendedCountries: 'Australia, Selandia Baru, Kanada.', whyTitle: 'Mengapa Nomor Telepon Diperlukan', whyUS: 'Amerika Serikat: Berdasarkan aturan tarif saat ini untuk kiriman pos, detail kontak penerima mungkin diperlukan untuk DDP/bea cukai dan pengiriman.', whyEU: 'Uni Eropa: Prosedur IOSS VAT dapat memerlukan kontak penerima untuk pemrosesan VAT dan koordinasi pengiriman.', whyUK: 'Inggris, Swiss, Norwegia: Prosedur VAT/bea cukai dapat memerlukan kontak pembeli untuk klarifikasi.', whyStrict: 'Tiongkok, India, Indonesia, Filipina, Korea Selatan, Taiwan, Vietnam: yurisdiksi bea cukai ketat dapat meminta nomor penerima untuk verifikasi deklarasi.', closing: 'Nomor yang valid membantu mencegah keterlambatan, gagal kirim, dan retur. Bea cukai atau kurir lokal dapat menghubungi penerima untuk klarifikasi.', importantLabel: 'Penting:', important: 'Tanpa nomor penerima, kiriman dapat tertunda, dikembalikan ke pengirim, atau pesanan dibatalkan.' },
  ga: { title: 'Uimhir theileafóin riachtanach don loingseoireacht (Tábhachtach)', intro: 'I gcás cinn scríbe áirithe, tá uimhir bhailí an fhaighteora éigeantach do sheoltaí Etsy. Cabhraíonn sé seo le custam, CBL/cáin agus seachadadh deiridh.', requiredTitle: 'Tíortha éigeantacha', requiredCountries: ['Stáit Aontaithe Mheiriceá', 'tíortha an Aontais Eorpaigh (thíos)', 'An Ríocht Aontaithe', 'An Iorua', 'An Eilvéis', 'An tSín', 'An India', 'An Indinéis', 'Na hOileáin Fhilipíneacha', 'An Chóiré Theas', 'An Téaváin', 'Vítneam'], euTitle: 'Tíortha an Aontais Eorpaigh', euCountries: 'An Ostair, an Bheilg, an tSeicia, an Fhionlainn, an Fhrainc, an Ghearmáin, Éire, an Iodáil, an Ísiltír, an Pholainn, an Phortaingéil, an Spáinn, an tSualainn.', recommendedTitle: 'Molta (ach ní éigeantach)', recommendedCountries: 'An Astráil, an Nua-Shéalainn, Ceanada.', whyTitle: 'Cén fáth a bhfuil uimhir theileafóin riachtanach', whyUS: 'SAM: Faoi rialacha taraife reatha do sheoltaí poist, d’fhéadfadh sonraí teagmhála an fhaighteora a bheith riachtanach do DDP/custam agus seachadadh.', whyEU: 'AE: D’fhéadfadh nósanna imeachta CBL IOSS teagmháil an fhaighteora a éileamh do phróiseáil CBL agus comhordú seachadta.', whyUK: 'An RA, an Eilvéis, an Iorua: D’fhéadfadh nósanna imeachta CBL/custaim teagmháil an cheannaitheora a éileamh le haghaidh soiléirithe.', whyStrict: 'An tSín, an India, an Indinéis, na hOileáin Fhilipíneacha, an Chóiré Theas, an Téaváin, Vítneam: d’fhéadfadh córais chustaim dhian uimhir an fhaighteora a iarraidh le dearbhuithe a fhíorú.', closing: 'Cabhraíonn uimhir bhailí moilleanna, teipeanna seachadta agus fillteáin a sheachaint. D’fhéadfadh custam nó iompróir áitiúil teagmháil a dhéanamh leis an bhfaighteoir.', importantLabel: 'Tábhachtach:', important: 'Mura gcuirtear uimhir an fhaighteora ar fáil, d’fhéadfadh moill, filleadh ar an seoltóir nó cealú ordaithe tarlú.' },
  it: { title: 'Numero di telefono richiesto per la spedizione (Importante)', intro: 'Per alcune destinazioni, per le spedizioni Etsy è obbligatorio un numero valido del destinatario. Questo aiuta dogana, IVA/tasse e consegna finale.', requiredTitle: 'Paesi obbligatori', requiredCountries: ['Stati Uniti', 'paesi dell’Unione Europea (sotto)', 'Regno Unito', 'Norvegia', 'Svizzera', 'Cina', 'India', 'Indonesia', 'Filippine', 'Corea del Sud', 'Taiwan', 'Vietnam'], euTitle: 'Paesi dell’Unione Europea', euCountries: 'Austria, Belgio, Cechia, Finlandia, Francia, Germania, Irlanda, Italia, Paesi Bassi, Polonia, Portogallo, Spagna, Svezia.', recommendedTitle: 'Consigliato (ma non obbligatorio)', recommendedCountries: 'Australia, Nuova Zelanda, Canada.', whyTitle: 'Perché è richiesto un numero di telefono', whyUS: 'Stati Uniti: secondo le regole tariffarie attuali per spedizioni postali, i contatti del destinatario possono essere richiesti per DDP/dogana e consegna.', whyEU: 'Unione Europea: le procedure IOSS IVA possono richiedere i contatti del destinatario per elaborazione IVA e coordinamento consegna.', whyUK: 'Regno Unito, Svizzera, Norvegia: le procedure IVA/doganali possono richiedere contatto con l’acquirente per chiarimenti.', whyStrict: 'Cina, India, Indonesia, Filippine, Corea del Sud, Taiwan, Vietnam: giurisdizioni doganali rigide possono richiedere numero del destinatario per verificare dichiarazioni.', closing: 'Un numero valido aiuta a prevenire ritardi, tentativi di consegna falliti e resi. Dogana o corriere locale possono contattare il destinatario.', importantLabel: 'Importante:', important: 'Senza numero del destinatario, la spedizione può subire ritardi, ritorno al mittente o annullamento ordine.' },
  mi: { title: 'Me tuku nama waea mō te tuku (He mea nui)', intro: 'Mō ētahi ūnga, me whai nama waea whaimana te kaiwhiwhi mō ngā tukunga Etsy. Ka āwhina tēnei i te tikanga kāwana, VAT/tāke, me te tuku whakamutunga.', requiredTitle: 'Ngā whenua me tuku', requiredCountries: ['United States', 'ngā whenua o te Uniana Ūropi (kei raro)', 'United Kingdom', 'Nōwei', 'Huiterangi', 'Haina', 'Inia', 'Inōnehia', 'Piripīni', 'Kōrea ki te Tonga', 'Taiwana', 'Wīetina'], euTitle: 'Ngā whenua o te Uniana Ūropi', euCountries: 'Āteria, Peretiamu, Tekeia, Whinarana, Wīwī, Tiamana, Airangi, Ītari, Hōrana, Pōrana, Potukara, Paniora, Huitene.', recommendedTitle: 'E taunakihia ana (ehara i te here)', recommendedCountries: 'Ahitereiria, Aotearoa, Kānata.', whyTitle: 'He aha i hiahiatia ai te nama waea', whyUS: 'United States: i raro i ngā ture tāke o nāianei mō ngā tuku mēra, ka hiahiatia pea ngā taipitopito whakapā mō te DDP/kāwana me te tuku.', whyEU: 'Uniana Ūropi: ka taea e ngā tukanga IOSS VAT te tono kōrero whakapā mō te tukatuka VAT me te whakarite tuku.', whyUK: 'United Kingdom, Huiterangi, Nōwei: ka taea e ngā tukanga VAT/kāwana te tono whakapā ki te kaihoko mō te whakamārama.', whyStrict: 'Haina, Inia, Inōnehia, Piripīni, Kōrea ki te Tonga, Taiwana, Wīetina: he kaha ngā ture kāwana, ka tono pea i te nama kaiwhiwhi hei manatoko tauākī.', closing: 'Ka āwhina te nama whaimana ki te karo i ngā whakaroanga, tukunga rahua me ngā whakahokinga. Ka whakapā mai pea te kāwana, te kaikawe ā-rohe rānei.', importantLabel: 'He mea nui:', important: 'Mēnā kāore he nama kaiwhiwhi, ka whakaroa pea te tuku, ka hoki rānei ki te kaituku, ka whakakorea rānei te tono.' },
  ja: { title: '配送には電話番号が必要です（重要）', intro: '一部の配送先では、Etsy発送に有効な受取人電話番号が必須です。通関、VAT/税務、最終配送連絡のために必要です。', requiredTitle: '必須国', requiredCountries: ['米国', 'EU加盟国（下記）', '英国', 'ノルウェー', 'スイス', '中国', 'インド', 'インドネシア', 'フィリピン', '韓国', '台湾', 'ベトナム'], euTitle: 'EU加盟国', euCountries: 'オーストリア、ベルギー、チェコ、フィンランド、フランス、ドイツ、アイルランド、イタリア、オランダ、ポーランド、ポルトガル、スペイン、スウェーデン。', recommendedTitle: '推奨（必須ではありません）', recommendedCountries: 'オーストラリア、ニュージーランド、カナダ。', whyTitle: '電話番号が必要な理由', whyUS: '米国：現在の郵便関税処理では、DDP/通関および配送連絡のため受取人連絡先が必要になる場合があります。', whyEU: 'EU：IOSS VAT手続きで、VAT処理と配送調整のため受取人連絡先が必要になる場合があります。', whyUK: '英国・スイス・ノルウェー：VAT/通関手続きで確認のため購入者連絡が必要になる場合があります。', whyStrict: '中国・インド・インドネシア・フィリピン・韓国・台湾・ベトナム：厳格な通関地域では申告確認のため受取人番号を求められる場合があります。', closing: '有効な番号は遅延、配達失敗、返送の防止に役立ちます。税関や現地配送業者が受取人へ連絡する場合があります。', importantLabel: '重要：', important: '受取人番号がない場合、遅延・返送・注文キャンセルが発生する可能性があります。' },
  ko: { title: '배송 시 전화번호 필수 (중요)', intro: '일부 목적지는 Etsy 배송 시 수취인 유효 전화번호가 필수입니다. 통관, VAT/세금 처리 및 최종 배송 연락에 필요합니다.', requiredTitle: '필수 국가', requiredCountries: ['미국', '유럽연합 국가(아래)', '영국', '노르웨이', '스위스', '중국', '인도', '인도네시아', '필리핀', '대한민국', '대만', '베트남'], euTitle: '유럽연합 국가', euCountries: '오스트리아, 벨기에, 체코, 핀란드, 프랑스, 독일, 아일랜드, 이탈리아, 네덜란드, 폴란드, 포르투갈, 스페인, 스웨덴.', recommendedTitle: '권장 (필수 아님)', recommendedCountries: '호주, 뉴질랜드, 캐나다.', whyTitle: '전화번호가 필요한 이유', whyUS: '미국: 현재 우편 관세 처리 규정에 따라 DDP/통관 및 배송 연락을 위해 수취인 연락처가 필요할 수 있습니다.', whyEU: '유럽연합: IOSS VAT 절차에서 VAT 처리 및 배송 조정을 위해 수취인 연락처가 필요할 수 있습니다.', whyUK: '영국, 스위스, 노르웨이: VAT/통관 절차에서 확인을 위해 구매자 연락이 필요할 수 있습니다.', whyStrict: '중국, 인도, 인도네시아, 필리핀, 대한민국, 대만, 베트남: 엄격한 통관 지역으로 신고 확인을 위해 수취인 번호를 요청할 수 있습니다.', closing: '유효한 번호는 지연, 배송 실패, 반송을 줄이는 데 도움이 됩니다. 세관 또는 현지 배송사가 수취인에게 연락할 수 있습니다.', importantLabel: '중요:', important: '수취인 번호가 없으면 지연, 반송 또는 주문 취소가 발생할 수 있습니다.' },
  ms: { title: 'Nombor telefon diperlukan untuk penghantaran (Penting)', intro: 'Bagi destinasi tertentu, nombor telefon penerima yang sah adalah wajib untuk penghantaran Etsy. Ini membantu proses kastam, VAT/cukai dan komunikasi penghantaran akhir.', requiredTitle: 'Negara wajib', requiredCountries: ['Amerika Syarikat', 'negara Kesatuan Eropah (di bawah)', 'United Kingdom', 'Norway', 'Switzerland', 'China', 'India', 'Indonesia', 'Filipina', 'Korea Selatan', 'Taiwan', 'Vietnam'], euTitle: 'Negara Kesatuan Eropah', euCountries: 'Austria, Belgium, Czechia, Finland, Perancis, Jerman, Ireland, Itali, Belanda, Poland, Portugal, Sepanyol, Sweden.', recommendedTitle: 'Disyorkan (tidak wajib)', recommendedCountries: 'Australia, New Zealand, Kanada.', whyTitle: 'Mengapa nombor telefon diperlukan', whyUS: 'Amerika Syarikat: Di bawah peraturan tarif semasa bagi kiriman pos, maklumat hubungan penerima mungkin diperlukan untuk DDP/kastam dan penghantaran.', whyEU: 'Kesatuan Eropah: Prosedur IOSS VAT mungkin memerlukan maklumat hubungan penerima untuk pemprosesan VAT dan koordinasi penghantaran.', whyUK: 'United Kingdom, Switzerland, Norway: Prosedur VAT/kastam mungkin memerlukan hubungan dengan pembeli untuk penjelasan.', whyStrict: 'China, India, Indonesia, Filipina, Korea Selatan, Taiwan, Vietnam: bidang kuasa kastam yang ketat mungkin meminta nombor penerima untuk pengesahan deklarasi.', closing: 'Nombor yang sah membantu mengelakkan kelewatan, kegagalan penghantaran, dan pemulangan. Kastam atau kurier tempatan boleh menghubungi penerima untuk penjelasan.', importantLabel: 'Penting:', important: 'Tanpa nombor penerima, kiriman boleh tertangguh, dipulangkan kepada pengirim atau pesanan dibatalkan.' },
  no: { title: 'Telefonnummer kreves for frakt (Viktig)', intro: 'For enkelte destinasjoner er gyldig mottakernummer obligatorisk for Etsy-forsendelser. Dette hjelper toll, mva/skatt og sisteledd-levering.', requiredTitle: 'Obligatoriske land', requiredCountries: ['USA', 'EU-land (nedenfor)', 'Storbritannia', 'Norge', 'Sveits', 'Kina', 'India', 'Indonesia', 'Filippinene', 'Sør-Korea', 'Taiwan', 'Vietnam'], euTitle: 'EU-land', euCountries: 'Østerrike, Belgia, Tsjekkia, Finland, Frankrike, Tyskland, Irland, Italia, Nederland, Polen, Portugal, Spania, Sverige.', recommendedTitle: 'Anbefalt (ikke obligatorisk)', recommendedCountries: 'Australia, New Zealand, Canada.', whyTitle: 'Hvorfor telefonnummer kreves', whyUS: 'USA: Etter gjeldende tariffhåndtering for postforsendelser kan mottakerkontakt kreves for DDP/toll og levering.', whyEU: 'EU: IOSS mva-prosedyrer kan kreve mottakerkontakt for mva-behandling og leveringskoordinering.', whyUK: 'Storbritannia, Sveits, Norge: Mva-/tollprosedyrer kan kreve kontakt med kjøper for avklaringer.', whyStrict: 'Kina, India, Indonesia, Filippinene, Sør-Korea, Taiwan, Vietnam: strenge tolljurisdiksjoner kan be om mottakernummer for verifisering av deklarasjoner.', closing: 'Et gyldig nummer bidrar til å unngå forsinkelser, mislykkede leveringsforsøk og returer. Toll eller lokal transportør kan kontakte mottaker.', importantLabel: 'Viktig:', important: 'Manglende mottakernummer kan føre til forsinkelse, retur til avsender eller kansellering av bestilling.' },
  pl: { title: 'Numer telefonu wymagany do wysyłki (Ważne)', intro: 'Dla niektórych krajów docelowych ważny numer telefonu odbiorcy jest obowiązkowy dla wysyłek Etsy. Pomaga to w odprawie celnej, VAT/podatkach i doręczeniu.', requiredTitle: 'Kraje obowiązkowe', requiredCountries: ['Stany Zjednoczone', 'kraje UE (poniżej)', 'Wielka Brytania', 'Norwegia', 'Szwajcaria', 'Chiny', 'Indie', 'Indonezja', 'Filipiny', 'Korea Południowa', 'Tajwan', 'Wietnam'], euTitle: 'Kraje Unii Europejskiej', euCountries: 'Austria, Belgia, Czechy, Finlandia, Francja, Niemcy, Irlandia, Włochy, Niderlandy, Polska, Portugalia, Hiszpania, Szwecja.', recommendedTitle: 'Zalecane (ale niewymagane)', recommendedCountries: 'Australia, Nowa Zelandia, Kanada.', whyTitle: 'Dlaczego numer telefonu jest wymagany', whyUS: 'USA: Zgodnie z aktualnymi zasadami taryfowymi dla przesyłek pocztowych, kontakt do odbiorcy może być wymagany dla DDP/cła i dostawy.', whyEU: 'UE: Procedury IOSS VAT mogą wymagać kontaktu odbiorcy do przetwarzania VAT i koordynacji dostawy.', whyUK: 'Wielka Brytania, Szwajcaria, Norwegia: Procedury VAT/celne mogą wymagać kontaktu z kupującym dla wyjaśnień.', whyStrict: 'Chiny, Indie, Indonezja, Filipiny, Korea Południowa, Tajwan, Wietnam: surowe jurysdykcje celne mogą żądać numeru odbiorcy do weryfikacji deklaracji.', closing: 'Ważny numer pomaga zapobiegać opóźnieniom, nieudanym doręczeniom i zwrotom. Urząd celny lub lokalny przewoźnik może skontaktować się z odbiorcą.', importantLabel: 'Ważne:', important: 'Brak numeru odbiorcy może spowodować opóźnienie, zwrot do nadawcy lub anulowanie zamówienia.' },
  pt: { title: 'Número de telefone obrigatório para envio (Importante)', intro: 'Para certos destinos, um número válido do destinatário é obrigatório nas remessas Etsy. Isso ajuda em alfândega, IVA/impostos e entrega final.', requiredTitle: 'Países obrigatórios', requiredCountries: ['Estados Unidos', 'países da União Europeia (abaixo)', 'Reino Unido', 'Noruega', 'Suíça', 'China', 'Índia', 'Indonésia', 'Filipinas', 'Coreia do Sul', 'Taiwan', 'Vietname'], euTitle: 'Países da União Europeia', euCountries: 'Áustria, Bélgica, Chéquia, Finlândia, França, Alemanha, Irlanda, Itália, Países Baixos, Polónia, Portugal, Espanha, Suécia.', recommendedTitle: 'Recomendado (mas não obrigatório)', recommendedCountries: 'Austrália, Nova Zelândia, Canadá.', whyTitle: 'Porque o número de telefone é obrigatório', whyUS: 'Estados Unidos: De acordo com o tratamento tarifário atual para remessas postais, o contacto do destinatário pode ser necessário para DDP/alfândega e entrega.', whyEU: 'União Europeia: Procedimentos de IVA IOSS podem exigir contacto do destinatário para processamento de IVA e coordenação da entrega.', whyUK: 'Reino Unido, Suíça, Noruega: Procedimentos de IVA/alfândega podem exigir contacto do comprador para esclarecimentos.', whyStrict: 'China, Índia, Indonésia, Filipinas, Coreia do Sul, Taiwan, Vietname: jurisdições alfandegárias rigorosas podem solicitar número do destinatário para verificar declarações.', closing: 'Um número válido ajuda a evitar atrasos, tentativas de entrega falhadas e devoluções. A alfândega ou transportadora local pode contactar o destinatário.', importantLabel: 'Importante:', important: 'A falta do número do destinatário pode resultar em atraso, devolução ao remetente ou cancelamento da encomenda.' },
  ru: { title: 'Телефон обязателен для доставки (Важно)', intro: 'Для некоторых направлений в отправлениях Etsy обязателен действующий номер получателя. Это помогает с таможней, НДС/налогами и последней милей доставки.', requiredTitle: 'Обязательные страны', requiredCountries: ['США', 'страны ЕС (ниже)', 'Великобритания', 'Норвегия', 'Швейцария', 'Китай', 'Индия', 'Индонезия', 'Филиппины', 'Южная Корея', 'Тайвань', 'Вьетнам'], euTitle: 'Страны Европейского союза', euCountries: 'Австрия, Бельгия, Чехия, Финляндия, Франция, Германия, Ирландия, Италия, Нидерланды, Польша, Португалия, Испания, Швеция.', recommendedTitle: 'Рекомендуется (но не обязательно)', recommendedCountries: 'Австралия, Новая Зеландия, Канада.', whyTitle: 'Почему требуется номер телефона', whyUS: 'США: По текущим правилам тарифной обработки почтовых отправлений контакт получателя может требоваться для DDP/таможни и доставки.', whyEU: 'ЕС: Процедуры IOSS VAT могут требовать контакт получателя для обработки НДС и координации доставки.', whyUK: 'Великобритания, Швейцария, Норвегия: Процедуры VAT/таможни могут требовать связи с покупателем для уточнений.', whyStrict: 'Китай, Индия, Индонезия, Филиппины, Южная Корея, Тайвань, Вьетнам: строгие таможенные юрисдикции могут запрашивать номер получателя для проверки деклараций.', closing: 'Действующий номер помогает предотвратить задержки, неудачные попытки доставки и возвраты. Таможня или местный перевозчик могут связаться с получателем.', importantLabel: 'Важно:', important: 'Отсутствие номера получателя может привести к задержке, возврату отправителю или отмене заказа.' },
  es: { title: 'Número de teléfono obligatorio para envíos (Importante)', intro: 'Para ciertos destinos, un teléfono válido del destinatario es obligatorio en envíos Etsy. Esto ayuda con aduanas, IVA/impuestos y entrega final.', requiredTitle: 'Países obligatorios', requiredCountries: ['Estados Unidos', 'países de la Unión Europea (abajo)', 'Reino Unido', 'Noruega', 'Suiza', 'China', 'India', 'Indonesia', 'Filipinas', 'Corea del Sur', 'Taiwán', 'Vietnam'], euTitle: 'Países de la Unión Europea', euCountries: 'Austria, Bélgica, Chequia, Finlandia, Francia, Alemania, Irlanda, Italia, Países Bajos, Polonia, Portugal, España, Suecia.', recommendedTitle: 'Recomendado (pero no obligatorio)', recommendedCountries: 'Australia, Nueva Zelanda, Canadá.', whyTitle: 'Por qué se requiere número de teléfono', whyUS: 'Estados Unidos: Según el tratamiento arancelario actual para envíos postales, los datos de contacto del destinatario pueden ser necesarios para DDP/aduanas y entrega.', whyEU: 'Unión Europea: Los procedimientos IOSS IVA pueden requerir contacto del destinatario para el procesamiento de IVA y coordinación de entrega.', whyUK: 'Reino Unido, Suiza, Noruega: Los procedimientos de IVA/aduanas pueden requerir contacto del comprador para aclaraciones.', whyStrict: 'China, India, Indonesia, Filipinas, Corea del Sur, Taiwán, Vietnam: jurisdicciones aduaneras estrictas pueden solicitar teléfono del destinatario para verificar declaraciones.', closing: 'Un número válido ayuda a evitar retrasos, intentos fallidos de entrega y devoluciones. Aduanas o transportista local pueden contactar al destinatario.', importantLabel: 'Importante:', important: 'Sin teléfono del destinatario, puede haber retraso, devolución al remitente o cancelación del pedido.' },
  sv: { title: 'Telefonnummer krävs för frakt (Viktigt)', intro: 'För vissa destinationer krävs ett giltigt mottagarnummer för Etsy-försändelser. Det hjälper med tull, moms/skatt och sista milen-leverans.', requiredTitle: 'Obligatoriska länder', requiredCountries: ['USA', 'EU-länder (nedan)', 'Storbritannien', 'Norge', 'Schweiz', 'Kina', 'Indien', 'Indonesien', 'Filippinerna', 'Sydkorea', 'Taiwan', 'Vietnam'], euTitle: 'Europeiska unionens länder', euCountries: 'Österrike, Belgien, Tjeckien, Finland, Frankrike, Tyskland, Irland, Italien, Nederländerna, Polen, Portugal, Spanien, Sverige.', recommendedTitle: 'Rekommenderas (men inte obligatoriskt)', recommendedCountries: 'Australien, Nya Zeeland, Kanada.', whyTitle: 'Varför telefonnummer krävs', whyUS: 'USA: Enligt nuvarande tull-/tariffhantering för postförsändelser kan mottagarkontakt krävas för DDP/tull och leverans.', whyEU: 'EU: IOSS-momsförfaranden kan kräva mottagarkontakt för momsbehandling och leveranssamordning.', whyUK: 'Storbritannien, Schweiz, Norge: Moms-/tullförfaranden kan kräva kontakt med köparen för förtydliganden.', whyStrict: 'Kina, Indien, Indonesien, Filippinerna, Sydkorea, Taiwan, Vietnam: strikta tulljurisdiktioner kan begära mottagarnummer för att verifiera deklarationer.', closing: 'Ett giltigt nummer hjälper till att undvika förseningar, misslyckade leveransförsök och returer. Tull eller lokal transportör kan kontakta mottagaren.', importantLabel: 'Viktigt:', important: 'Saknat mottagarnummer kan leda till försening, retur till avsändare eller annullering.' },
  ta: { title: 'அனுப்புதலுக்கு தொலைபேசி எண் அவசியம் (முக்கியம்)', intro: 'சில இலக்குகளுக்கான Etsy அனுப்புதல்களில் பெறுநரின் செல்லுபடியாகும் தொலைபேசி எண் கட்டாயம். இது சுங்கம், VAT/வரி மற்றும் இறுதி விநியோக ஒத்துழைப்பிற்கு உதவுகிறது.', requiredTitle: 'கட்டாய நாடுகள்', requiredCountries: ['அமெரிக்கா', 'ஐரோப்பிய ஒன்றிய நாடுகள் (கீழே)', 'இங்கிலாந்து', 'நார்வே', 'சுவிட்சர்லாந்து', 'சீனா', 'இந்தியா', 'இந்தோனேஷியா', 'பிலிப்பைன்ஸ்', 'தென் கொரியா', 'தைவான்', 'வியட்நாம்'], euTitle: 'ஐரோப்பிய ஒன்றிய நாடுகள்', euCountries: 'ஆஸ்திரியா, பெல்ஜியம், செக், பின்லாந்து, பிரான்ஸ், ஜெர்மனி, அயர்லாந்து, இத்தாலி, நெதர்லாந்து, போலந்து, போர்ச்சுகல், ஸ்பெயின், ஸ்வீடன்.', recommendedTitle: 'பரிந்துரைக்கப்படுகிறது (ஆனால் கட்டாயம் இல்லை)', recommendedCountries: 'ஆஸ்திரேலியா, நியூசிலாந்து, கனடா.', whyTitle: 'ஏன் தொலைபேசி எண் அவசியம்', whyUS: 'அமெரிக்கா: அஞ்சல் அனுப்புதலுக்கான தற்போதைய சுங்க/வரி நடைமுறைகளின் கீழ் DDP/சுங்கம் மற்றும் விநியோக தொடர்புக்கு பெறுநர் தொடர்பு தேவைப்படலாம்.', whyEU: 'ஐரோப்பிய ஒன்றியம்: IOSS VAT நடைமுறைகள் VAT செயலாக்கம் மற்றும் விநியோக ஒத்துழைப்புக்கு பெறுநர் தொடர்பை கோரலாம்.', whyUK: 'இங்கிலாந்து, சுவிட்சர்லாந்து, நார்வே: VAT/சுங்க நடைமுறைகளில் விளக்கம் பெற வாங்குபவரை தொடர்பு கொள்ள வேண்டி இருக்கலாம்.', whyStrict: 'சீனா, இந்தியா, இந்தோனேஷியா, பிலிப்பைன்ஸ், தென் கொரியா, தைவான், வியட்நாம்: கடுமையான சுங்க விதிகள் காரணமாக அறிவிப்புகளை சரிபார்க்க பெறுநர் எண் கேட்கப்படலாம்.', closing: 'செல்லுபடியாகும் எண் தாமதம், விநியோக தோல்வி மற்றும் திருப்பி அனுப்புதலை தவிர்க்க உதவும். சுங்கம் அல்லது உள்ளூர் குரியர் பெறுநரை தொடர்பு கொள்ளலாம்.', importantLabel: 'முக்கியம்:', important: 'பெறுநர் எண் இல்லையெனில் தாமதம், அனுப்புநருக்கு திருப்பு அல்லது ஆர்டர் ரத்து ஏற்படலாம்.' },
  tl: { title: 'Kailangan ang phone number para sa shipping (Mahalaga)', intro: 'Para sa ilang destinasyon, kailangan ang valid na numero ng recipient para sa Etsy shipments. Nakakatulong ito sa customs, VAT/buwis, at final delivery communication.', requiredTitle: 'Mga Bansang Kailangan', requiredCountries: ['United States', 'mga bansa sa European Union (nasa ibaba)', 'United Kingdom', 'Norway', 'Switzerland', 'China', 'India', 'Indonesia', 'Philippines', 'South Korea', 'Taiwan', 'Vietnam'], euTitle: 'Mga Bansa sa European Union', euCountries: 'Austria, Belgium, Czechia, Finland, France, Germany, Ireland, Italy, Netherlands, Poland, Portugal, Spain, Sweden.', recommendedTitle: 'Inirerekomenda (pero hindi kailangan)', recommendedCountries: 'Australia, New Zealand, Canada.', whyTitle: 'Bakit kailangan ang phone number', whyUS: 'United States: Sa kasalukuyang tariff handling para sa postal shipments, maaaring kailanganin ang contact details ng recipient para sa DDP/customs at delivery communication.', whyEU: 'European Union: Maaaring kailanganin ng IOSS VAT procedures ang recipient contact details para sa VAT processing at delivery coordination.', whyUK: 'United Kingdom, Switzerland, Norway: Maaaring kailanganin ng VAT/customs procedures ang buyer contact para sa paglilinaw.', whyStrict: 'China, India, Indonesia, Philippines, South Korea, Taiwan, Vietnam: mahigpit na customs jurisdictions na maaaring humingi ng recipient phone details para sa verification ng declarations.', closing: 'Ang valid na numero ay tumutulong maiwasan ang delays, failed delivery attempts, at returns. Maaaring makipag-ugnayan ang customs o local courier sa recipient para sa karagdagang detalye.', importantLabel: 'Mahalaga:', important: 'Kapag walang recipient phone number, maaaring ma-delay ang shipment, ma-return to sender, o ma-cancel ang order.' },
  th: { title: 'จำเป็นต้องมีหมายเลขโทรศัพท์สำหรับการจัดส่ง (สำคัญ)', intro: 'สำหรับบางปลายทาง คำสั่งซื้อ Etsy จำเป็นต้องมีหมายเลขผู้รับที่ถูกต้อง เพื่อช่วยด้านศุลกากร VAT/ภาษี และการประสานงานจัดส่งปลายทาง', requiredTitle: 'ประเทศที่บังคับ', requiredCountries: ['สหรัฐอเมริกา', 'ประเทศสหภาพยุโรป (ด้านล่าง)', 'สหราชอาณาจักร', 'นอร์เวย์', 'สวิตเซอร์แลนด์', 'จีน', 'อินเดีย', 'อินโดนีเซีย', 'ฟิลิปปินส์', 'เกาหลีใต้', 'ไต้หวัน', 'เวียดนาม'], euTitle: 'ประเทศในสหภาพยุโรป', euCountries: 'ออสเตรีย เบลเยียม เช็ก ฟินแลนด์ ฝรั่งเศส เยอรมนี ไอร์แลนด์ อิตาลี เนเธอร์แลนด์ โปแลนด์ โปรตุเกส สเปน สวีเดน', recommendedTitle: 'แนะนำ (แต่ไม่บังคับ)', recommendedCountries: 'ออสเตรเลีย นิวซีแลนด์ แคนาดา', whyTitle: 'เหตุผลที่ต้องใช้หมายเลขโทรศัพท์', whyUS: 'สหรัฐอเมริกา: ตามกฎภาษีปัจจุบันสำหรับพัสดุไปรษณีย์ อาจต้องใช้ข้อมูลติดต่อผู้รับสำหรับ DDP/ศุลกากรและการจัดส่ง', whyEU: 'สหภาพยุโรป: ขั้นตอน IOSS VAT อาจต้องใช้ข้อมูลติดต่อผู้รับเพื่อประมวลผล VAT และประสานงานการจัดส่ง', whyUK: 'สหราชอาณาจักร สวิตเซอร์แลนด์ นอร์เวย์: ขั้นตอน VAT/ศุลกากรอาจต้องติดต่อผู้ซื้อเพื่อชี้แจงข้อมูล', whyStrict: 'จีน อินเดีย อินโดนีเซีย ฟิลิปปินส์ เกาหลีใต้ ไต้หวัน เวียดนาม: เขตศุลกากรเข้มงวดที่อาจขอหมายเลขผู้รับเพื่อยืนยันเอกสารสำแดง', closing: 'หมายเลขที่ถูกต้องช่วยลดความล่าช้า ความล้มเหลวในการจัดส่ง และการตีกลับพัสดุ ศุลกากรหรือผู้ให้บริการท้องถิ่นอาจติดต่อผู้รับเพื่อข้อมูลเพิ่มเติม', importantLabel: 'สำคัญ:', important: 'หากไม่มีหมายเลขผู้รับ อาจเกิดความล่าช้า ตีกลับไปผู้ส่ง หรือยกเลิกคำสั่งซื้อ' },
  vi: { title: 'Bắt buộc số điện thoại khi gửi hàng (Quan trọng)', intro: 'Với một số điểm đến, đơn Etsy bắt buộc có số điện thoại người nhận hợp lệ. Điều này giúp thông quan, xử lý VAT/thuế và phối hợp giao hàng chặng cuối.', requiredTitle: 'Các quốc gia bắt buộc', requiredCountries: ['Hoa Kỳ', 'các nước Liên minh Châu Âu (bên dưới)', 'Vương quốc Anh', 'Na Uy', 'Thụy Sĩ', 'Trung Quốc', 'Ấn Độ', 'Indonesia', 'Philippines', 'Hàn Quốc', 'Đài Loan', 'Việt Nam'], euTitle: 'Các nước Liên minh Châu Âu', euCountries: 'Áo, Bỉ, Czechia, Phần Lan, Pháp, Đức, Ireland, Ý, Hà Lan, Ba Lan, Bồ Đào Nha, Tây Ban Nha, Thụy Điển.', recommendedTitle: 'Khuyến nghị (không bắt buộc)', recommendedCountries: 'Úc, New Zealand, Canada.', whyTitle: 'Vì sao cần số điện thoại', whyUS: 'Hoa Kỳ: Theo quy định xử lý thuế hiện hành cho bưu gửi, thông tin liên hệ người nhận có thể cần cho DDP/hải quan và giao hàng.', whyEU: 'Liên minh Châu Âu: Quy trình IOSS VAT có thể yêu cầu liên hệ người nhận để xử lý VAT và điều phối giao hàng.', whyUK: 'Vương quốc Anh, Thụy Sĩ, Na Uy: Quy trình VAT/hải quan có thể yêu cầu liên hệ người mua để làm rõ thông tin.', whyStrict: 'Trung Quốc, Ấn Độ, Indonesia, Philippines, Hàn Quốc, Đài Loan, Việt Nam: khu vực hải quan nghiêm ngặt có thể yêu cầu số người nhận để xác minh khai báo.', closing: 'Số hợp lệ giúp giảm chậm trễ, giao hàng thất bại và hoàn trả. Hải quan hoặc đơn vị vận chuyển địa phương có thể liên hệ người nhận để xác minh.', importantLabel: 'Quan trọng:', important: 'Thiếu số người nhận có thể gây chậm trễ, hoàn về người gửi hoặc hủy đơn.' },
  cy: { title: 'Mae rhif ffôn yn ofynnol ar gyfer cludo (Pwysig)', intro: 'Ar gyfer rhai cyrchfannau, mae rhif derbynnydd dilys yn orfodol ar gyfer cludiant Etsy. Mae hyn yn helpu gyda thollau, TAW/treth, a chyfathrebu danfon terfynol.', requiredTitle: 'Gwledydd gorfodol', requiredCountries: ['Yr Unol Daleithiau', 'gwledydd yr Undeb Ewropeaidd (isod)', 'Y Deyrnas Unedig', 'Norwy', 'Y Swistir', 'Tsieina', 'India', 'Indonesia', 'Ynysoedd y Philipinau', 'De Corea', 'Taiwan', 'Fietnam'], euTitle: 'Gwledydd yr Undeb Ewropeaidd', euCountries: 'Awstria, Gwlad Belg, Tsiecia, y Ffindir, Ffrainc, yr Almaen, Iwerddon, yr Eidal, yr Iseldiroedd, Gwlad Pwyl, Portiwgal, Sbaen, Sweden.', recommendedTitle: 'Argymhellir (ond nid yw’n orfodol)', recommendedCountries: 'Awstralia, Seland Newydd, Canada.', whyTitle: 'Pam mae rhif ffôn yn ofynnol', whyUS: 'Yr Unol Daleithiau: O dan reolau tariff presennol ar gludiant post, gall manylion cyswllt y derbynnydd fod yn ofynnol ar gyfer DDP/tollau a danfon.', whyEU: 'Undeb Ewropeaidd: Gall gweithdrefnau TAW IOSS ofyn am gyswllt derbynnydd ar gyfer prosesu TAW a chydlynu danfon.', whyUK: 'Y Deyrnas Unedig, y Swistir, Norwy: Gall gweithdrefnau TAW/tollau ofyn am gyswllt y prynwr ar gyfer eglurhad.', whyStrict: 'Tsieina, India, Indonesia, Ynysoedd y Philipinau, De Corea, Taiwan, Fietnam: awdurdodaethau tollau llym a all ofyn am rif derbynnydd i wirio datganiadau.', closing: 'Mae rhif dilys yn helpu i atal oedi, methiannau danfon a dychweliadau. Gall tollau neu gludwr lleol gysylltu â’r derbynnydd i egluro manylion.', importantLabel: 'Pwysig:', important: 'Heb rif derbynnydd, gall y llwyth gael ei oedi, ei ddychwelyd i’r anfonwr, neu gall yr archeb gael ei chanslo.' },
};

function getBlogContentByLanguage(languageCode) {
  const normalized = String(languageCode || 'en').toLowerCase();
  if (normalized === 'zh-tw' || normalized === 'zh-hk' || normalized === 'zh-hant') {
    return BLOG_PHONE_REQUIREMENT_I18N['zh-hant'];
  }
  if (normalized.startsWith('zh')) {
    return BLOG_PHONE_REQUIREMENT_I18N.zh;
  }
  return BLOG_PHONE_REQUIREMENT_I18N[normalized] || BLOG_PHONE_REQUIREMENT_I18N.en;
}

export default function PhoneNumberRequiredBlog() {
  const { language } = useLanguage();
  const content = getBlogContentByLanguage(language);

  return (
    <BlogPageLayout>
      <h2>{content.title}</h2>

      <p>{content.intro}</p>

      <h4>{content.requiredTitle}</h4>
      <ul>
        {content.requiredCountries.map((country) => (
          <li key={country}>{country}</li>
        ))}
      </ul>

      <h4>{content.euTitle}</h4>
      <p>{content.euCountries}</p>

      <h4>{content.recommendedTitle}</h4>
      <p>{content.recommendedCountries}</p>

      <h4>{content.whyTitle}</h4>
      <ul>
        <li>{content.whyUS}</li>
        <li>{content.whyEU}</li>
        <li>{content.whyUK}</li>
        <li>{content.whyStrict}</li>
      </ul>

      <p>{content.closing}</p>

      <p>
        <strong>{content.importantLabel}</strong> {content.important}
      </p>
    </BlogPageLayout>
  );
}
